### ISSUE TITLE
Multiple AWS accounts in .credentials 

### ISSUE THREAD

**Issue by cu12** [jantman/awslimitchecker#108]
This seems to be unsupported at the moment, as I see, the tool only checks for the [default] entry and does not use the region= entry neither, see:

```
✗ awslimitchecker -W 20
awslimitchecker 0.2.2@c9cf054 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker.git>
```

```
✗ awslimitchecker -r <region> -W 20
awslimitchecker 0.2.2@c9cf054 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker.git>
AutoScaling/Auto Scaling groups                        (limit 20) WARNING: 6
EC2/Elastic IP addresses (EIPs)                        (limit 15) WARNING: 7
EC2/Running On-Demand c3.large instances               (limit 20) WARNING: 4
EC2/VPC security groups per elastic network interface  (limit 5) WARNING: <redacted>
ElastiCache/Parameter Groups                           (limit 20) WARNING: 4
RDS/DB snapshots per user                              (limit 50) WARNING: 13
VPC/Internet gateways                                  (limit 5) WARNING: 2
VPC/Rules per network ACL                              (limit 20) WARNING: <redacted>
VPC/VPCs                                               (limit 5) WARNING: 2
```

**Comment by jantman** [comment]
I'm not entirely sure what ``.credentials`` is - are you referring to ``.aws/credentials``?

Documentation on credentials is available at https://awslimitchecker.readthedocs.org/en/latest/getting_started.html#credentials but generally, it supports anything used by [boto](http://docs.pythonboto.org/en/latest/boto_config_tut.html).

To specify a ``.aws/credentials`` section other than ``default``, set the ``AWS_PROFILE`` environment variable to the name of the section. I have *not* tested region handling in the config file; the expected use is to set a region with the ``-r REGION_NAME`` argument to awslimitchecker.

Has this answered your question? Is there something else that I've missed?

PS - if you post code snippets/command line output, please run with ``-vv`` for debug-level output.

Thanks,
Jason

**Comment by jantman** [comment]
@cu12 when you have a chance, please confirm my understanding of your issue is correct. I'm going to hold off on cutting a release for #107 until I'm clear on whether this issue just needs better documentation, or needs a code fix.

**Comment by cu12** [comment]
@jantman Thanks that's answers my question, thanks for the quick reply :+1:

**Comment by jantman** [comment]
Ok, thanks!
