### ISSUE TITLE
Expand integration tests

### ISSUE THREAD

**Issue by jantman** [jantman/awslimitchecker#114]
Integration tests should also run for other regions, STS, threshold override, limit overrides and skip-ta.

**Comment by jantman** [comment]
Also, should save output, grep for warning or higher but not TA subscription.

**Comment by jantman** [comment]
For STS, I can try two things: one, use a normal cross-account link, and two, try to use something like [onetimepass](https://github.com/tadeck/onetimepass) or [pyotp](https://github.com/pyotp/pyotp) to auth with an MFA device.

**Comment by jantman** [comment]
Also, while these credentials have very low privilege, I should see if there's a way to suppress printing of the credentials in the output of failed tests.

**Comment by jantman** [comment]
Also, look into:

1. Travis not running integration tests for PRs?
2. tox don't pass AWS_* to non-integration tests?

**Comment by jantman** [comment]
Remaining:

* other regions
* test threshold overrides?
* test limit overrides?
* test skip-ta?
* Also, should save output, grep for warning or higher but not TA subscription. Look into https://pypi.python.org/pypi/pytest-capturelog for this

**Comment by jantman** [comment]
This was merged to develop in #124

**Comment by nagireddy451** [comment]
Hello jantman,

I need one help as per document i created the cross account detials in my script but i am not able to execute the script.

here is my script:

for i in range(1,count):
#pdb.set_trace()
response2=client.get_item(TableName='AWSlimitchecker', Key={'S.No':{'N':str(i)}})
pprint.pprint(str(response2['Item']['Region']['S']))
reg = str(response2['Item']['Region']['S'])
pprint.pprint(str(response2['Item']['Role']['S']))
iamrole = str(response2['Item']['Role']['S'])
pprint.pprint(str(response2['Item']['Accountnumber']['N']))
Account = str(response2['Item']['Accountnumber']['N'])
pprint.pprint(str(response2['Item']['Customer']['S']))
cust = str(response2['Item']['Customer']['S'])
#pdb.set_trace()
**d = AwsLimitChecker(region=reg,account_id=Account,account_role=iamrole)**
result = d.check_thresholds()
temp1=result.keys()
#pdb.set_trace()
if len(temp1)>0:
for m in temp1:
temp2=result[m].keys()
print 'first loop : '+m
#pdb.set_trace()
for n in temp2:
#pdb.set_trace()
try:
a = str(result[m][n].get_warnings()[0].get_value())
print 'The limit regarding the service "'+m+'" with limit name "'+n+'" the current limit value is : '+a
response3 = notif.publish(

**Comment by jantman** [comment]
@nagireddy451 

1. Please open a new issue for this. This is unrelated to my "Expand integration tests" issue.
2. It appears that your paste above is incomplete, and certainly doesn't include the output. When you open the new issue, please follow the guidelines in the new issue template, which can also be seen [here](https://github.com/jantman/awslimitchecker/blob/master/.github/ISSUE_TEMPLATE.md#bug-report).

**Comment by jantman** [comment]
@nagireddy451 Looking at the above code, it seems that you're deploying awslimitchecker to monitor limits on customers' accounts? If so, I'll point you to the documentation section on [Enterprise support agreements and contract development](http://awslimitchecker.readthedocs.io/en/latest/getting_help.html#enterprise-support-agreements-and-contract-development).

**Comment by nagireddy451** [comment]
Yes you are right but i dont need any paid support at the moment please
help how to configure for cross account execution.
For now i provide account id, account number, cross account arn but i not
able to execute the module as per document you wrote.

Thanks in advance.

**Comment by jantman** [comment]
PLEASE OPEN A NEW ISSUE. What you are asking is not related to this one.

When you open that issue, please complete ALL fields in the template.
