### ISSUE TITLE
Credential issue

### ISSUE THREAD

**Issue by rohawamr** [jantman/awslimitchecker#122]
I have these parameters with me:
region 
aws_access_key_id 
aws_secret_access_key 
aws_session_token
expire

I am having trouble using credentials. Can you give me an example using these credential parameters.

**Comment by jantman** [comment]
@rohawamr how did you get those parameters? That looks to me like the [STS](https://docs.aws.amazon.com/STS/latest/APIReference/Welcome.html) [Credentials response type](https://docs.aws.amazon.com/STS/latest/APIReference/API_Credentials.html), i.e. what you'd get back from a [GetSessionToken](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html) or maybe [GetFederationToken](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetFederationToken.html) call. If that's the case, there are a few problems:

1. These are temporary credentials, so they'll have a limited lifetime (the default is 12 hours, and the maximum is 36 hours).
2. Right now, ``awslimitchecker`` doesn't have a way to pass in session credentials.

One option would be to just try without the session token, if they're not really session credentials:

```bash
export HISTCONTROL=ignorespace
 export AWS_ACCESS_KEY_ID=<value of aws_access_key_id>
 export AWS_SECRET_ACCESS_KEY=<value of aws_secret_access_key>
awslimitchecker -r <region>
```

There are two main assumptions which led to ``awslimitchecker`` not having the ability to authenticate with session credentials:

1. The assumption that ``awslimitchecker`` will be used by people with administrative access to the account.
2. The assumption that ``awslimitchecker`` will usually be run by some automated tool (i.e. a ``cron`` job or something like Jenkins or Rundeck), and therefore that limited-lifetime credentials will not be useful.

Assuming the above code doesn't work and these are, in fact, session or federation credentials, I believe that I can add support for this but it would take a few days.

**Comment by rohawamr** [comment]
Actually this was an issue during initial development phase where I had no IAM role set up for authentication of the AWSLimitchecker. And the only way I was allowed access to AWS resources was through token based authentication that in my case lasted for an hour.

You may want this added as a functionality to AWSLimitchecker. However, now I have setup the required IAM policy and am all good.

Thanks to this project, the interface of AWSLimitchecker is really good and has helped me a lot.

**Comment by jantman** [comment]
Ok. I'm very glad that you've found it useful. I've opened #123 to track this feature request, so hopefully people will have an easier time evaluating it in the future.

Also, just so you know, I plan on adding support for more services in the next few weeks.

-Jason

**Comment by jantman** [comment]
@rohawamr I'm sorry for this sitting open for so long, but I think I've found a workaround...

At least with the current version, 0.7.0, I can properly authenticate with STS tokens by exporting the ``AWS_ACCESS_KEY_ID``, ``AWS_SECRET_ACCESS_KEY`` and ``AWS_SESSION_TOKEN`` environment variables.
