### ISSUE TITLE
Ability to automatically request limit increases

### ISSUE THREAD

**Issue by jantman** [jantman/awslimitchecker#147]
I've had a number of users mention that they'd like it if awslimitchecker could automatically open limit increase support cases with AWS. It _seems_ like this should be possible, though it would require either storing state of opened limit increase requests, or querying support cases to ensure we don't open duplicates.

Another question is how to handle limits that we can't retrieve via the API or TrustedAdvisor; the options I can think of are:
1. Only support opening cases for limits that we can programmatically confirm (i.e. where we can verify if the increase happened or not, without manually updating limit overrides).
2. When we find a warning or crirical, retrieve and parse **all** limit increase support cases looking for a matching one.

We can create new cases using the [CreateCase](http://docs.aws.amazon.com/awssupport/latest/APIReference/API_CreateCase.html) Support API action. There's a `service-limit-increase` service code (retrieved via the [DescribeServices](http://docs.aws.amazon.com/awssupport/latest/APIReference/API_DescribeServices.html) action), which lists category codes for each of the services. I don't see any fields in the API call for the Limit Type, Region, Limit or New Value.

To query existing cases, use the [DescribeCases](http://docs.aws.amazon.com/awssupport/latest/APIReference/API_DescribeCases.html) action.

**Comment by jantman** [comment]
Looking at the output of ``DescribeCases`` in some accounts that I have access to, it seems that the Limit Increase-specific fields on the Create Case UI (Region, Limit, New limit value) simply template into the beginning of the body of the initial case. Some examples:

```
Limit increase request 1
Service: EBS
Region: US East (Northern Virginia)
Resource Type: Snapshots
Limit name: EBS Snapshots Limit
New limit value: 16000
------------
Use case description: <user entered text>
```

```
Limit increase request 1
Service: RDS Instances
Region: US East (Northern Virginia)
Limit name: DB Subnet Groups
New limit value: 200
------------
Use case description: <user entered text>
```

```
Limit increase request 1
Service: EC2 Instances
Region: US East (Northern Virginia)
Primary Instance Type: m4.large
Limit name: Instance Limit
New limit value: 60
------------
Use case description: <user entered text>
```

```
Limit increase request 1
Service: VPC
Region: US East (Northern Virginia)
Limit name: New VPC Elastic IP Address Limit
New limit value: 200
------------
Limit increase request 2
Service: VPC
Region: US East (Northern Virginia)
Limit name: Requested VPCs
New limit value: 20
------------
Use case description: <user entered text>
```

Note that each request must be for a distinct service.

**Comment by jantman** [comment]
This should allow us to open requests for only warnings, only criticals, both or neither. Perhaps we should also bump up the priority on criticals.

Should this be part of awslimitchecker proper (i.e. ``--open-requests=([none]|both|warning|critical)``) or a separate executable? If the latter, we'd need awslimitchecker to cache its output somewhere for the second script to use.

**Comment by jantman** [comment]
I added a very rough standalone example script to do this in 41cbaee

**Comment by minhtrieutbcm01** [comment]
Hello janman!

Can you tell me how to use it. 

I added a very rough standalone example script to do this in 41cbaee

**Comment by jantman** [comment]
Honestly, no. That's very quickly-written example code, and probably has high odds of doing something very bad to your AWS account, or at least upsetting AWS Support. I wouldn't recommend using it, if it's not clear what the script is trying to do. Sorry.

**Comment by minhtrieutbcm01** [comment]
My account and limit 2 x t2.
Can i make more ??

**Comment by minhtrieutbcm01** [comment]
Why not limit Running On-Demand EC2 instances 20 as before.
Am I wrong?

**Comment by jantman** [comment]
I have no idea, sorry. You would need to contact AWS Support about that. awslimitchecker does not yet have the ability to request limit increases.

**Comment by MarcusRosen** [comment]
I'm looking at building exactly this functionality. I was looking at using DynamoDB to support non-TA services or for AWS accounts that don't have Business or above support plans.

Looks like you can raise cases with a specific subject to notify AWS support you are testing only.
From: [About the AWS Support API](http://docs.aws.amazon.com/awssupport/latest/user/Welcome.html)

> Warning
>The AWS Support endpoint creates cases in the production database. Include a subject line such as "TEST CASE--Please ignore" when you call CreateCase for testing, and close the test cases you create by calling ResolveCase.

**Comment by jantman** [comment]
I'm closing this issue for now.

As far as I know, the [yipit/awslimits](https://github.com/Yipit/awslimits) web UI has this capability.

If someone else wants to have a try at a PR that's fine, but this is outside the scope of what I need out of the project.
