### ISSUE TITLE
Ready-to-run method in AWS?

### ISSUE THREAD

**Issue by jantman** [jantman/awslimitchecker#151]
Would it be possible to run awslimitchecker in [AWS Lambda](https://aws.amazon.com/lambda/)? If so, can we provide tooling to set that up, and trigger it either manually or via "cron", or via a command line script?

**Comment by dsumsky** [comment]
Last month, I was working on testing it with AWS Lambda. If you want I can provide results for general usage.

**Comment by jantman** [comment]
@dsumsky that would be absolutely wonderful!!! Thanks so much!

**Comment by asafcombo** [comment]
@dsumsky , would appreciate if you can share your lambda script/implementation. Tnx!

**Comment by jantman** [comment]
Capital One's [Cloud Custodian](https://github.com/capitalone/cloud-custodian) has a pretty nifty method of [deploying itself to Lambda](http://www.capitalone.io/cloud-custodian/docs/policy/mu.html) via [c7n.mu](https://github.com/capitalone/cloud-custodian/blob/master/c7n/mu.py) ([docs](http://www.capitalone.io/cloud-custodian/docs/generated/c7n.html#module-c7n.mu)). That might be a useful tool for this.

**Comment by jantman** [comment]
If anyone is interested in this feel free to comment or reopen (@dsumsky I'm interested in your results) but I don't think I'm going to be implementing this any time soon for my own purposes. PRs are always welcome.
