### ISSUE TITLE
statsd output for limits and usage

### ISSUE THREAD

**Issue by jantman** [jantman/awslimitchecker#152]
It would be useful if awslimitchecker could push metrics for current limits and current usage to a statsd server.

**Comment by sbasgall** [comment]
I am doing something similar with a wrapper script using AWS Lambda to push metrics for current limits and usage to a graphite server.

```python
import logging

from awslimitchecker.checker import AwsLimitChecker

import graphitesend


def main(event, context):
    """Collect and send AWS Limits to Hosted Graphite.

    Keyword arguments:
    event -- JSON Payload from Cloudwatch Event
	{
		"hg_config": {
			"key": "hosted_graphite api key",
			"domain": "carbon.hostedgraphite.com",
      "system_name": "awslimits"
		},
		"limits_config": {
			"region": "us-east-1",
			"account": "build",
			"use_ta": "True"
		}
	}
    context -- Runtime information object from Lambda service

    Returns:
    None"""

    logger = logging.getLogger()
    logger.setLevel(logging.ERROR)

    g_obj = graphitesend.init(
        graphite_server=event['hg_config']['domain'],
        prefix=event['hg_config']['key'],
        system_name=event['hg_config']['system_name'],
        autoreconnect=True,
        asynchronous=True,
        lowercase_metric_names=True,
        clean_metric_name=False,
    )

    use_ta = event['limits_config']['use_ta']
    region = event['limits_config']['region']
    account = event['limits_config']['account']

    checker = AwsLimitChecker(region=region)
    checker.find_usage(use_ta=use_ta)

    for service, svc_limits in sorted(checker.get_limits(use_ta=use_ta).items()):

        base_path = '.'.join([account, region, service])

        for limit_name, limit in sorted(svc_limits.items()):

            limit_metric = limit.get_limit()
            clean_limit_name = limit_name.replace(' ', '-').replace('.', '_')
            limit_path = '.'.join([base_path, clean_limit_name])

            for resource in limit.get_current_usage():

                limit_path_res = '.'.join([limit_path, resource.resource_id])

                if resource.resource_id:
                    g_obj.send(".".join([limit_path_res, 'limit']), limit_metric)
                    g_obj.send(".".join([limit_path_res, 'current']), resource.get_value())
                else:
                    g_obj.send(".".join([limit_path, 'limit']), limit_metric)
                    g_obj.send(".".join([limit_path, 'current']), resource.get_value())
```

Maybe it is appropriate to include this feature as an example script instead of an awslimitchecker program feature?

**Comment by sbasgall** [comment]
If this is something valuable to the project I can clean it up, align it better with your current example scripts, and submit a PR.

**Comment by jantman** [comment]
@sbasgall sorry I let this sit for so long.

So my thought is as follows:

1. If you could clean that up a bit, I'll add the script to the [docs/examples](https://github.com/jantman/awslimitchecker/tree/master/docs/examples) directory, and also mention it on the [Python Usage](http://awslimitchecker.readthedocs.io/en/latest/python_usage.html) page of the docs.
2. If there's any more interest expressed in this, perhaps I'll look into either building in support for this, or - more likely - building an [entrypoints](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#entry-points)-based plugin system, so code that executes after limits have been checked can be installed separately.

**Comment by sstarcher** [comment]
I would be interested in this.  What would the preferred implementation be?  It could be something as simple as a command for --statsd=uri

**Comment by sstarcher** [comment]
@jantman Would you be interested in an implementation using say https://github.com/prometheus/client_python

It supports prometheus by default, but also has a bridge setup to support graphite.

**Comment by jantman** [comment]
@sstarcher Sorry for the delay on responding, I've had some personal stuff going on that's precluded much work on my projects lately.

I'm thinking that ideally I'd like an implementation that's provider-agnostic; some abstract base class that defines an initializer and a send_metric method that takes a string service name, string limit name, usage value and limit value, and sends the metric. From the CLI, I assume it would be something like ``--metric-provider=ClassName`` and ``--metric-option=name=value`` (using [StoreKeyValuePair](https://github.com/jantman/awslimitchecker/blob/0.7.0/awslimitchecker/utils.py#L47) for the options). The idea being that adding a new metric provider (other than Prometheus or statsd/graphite) would be as simple as adding a class that meets a specified interface.

I can probably get started on an initial implementation of this in the next week or two... My main points would be:

* Clearly documented how to create a class that implements a metric provider, and add tests for it.
* MetricProvider abstract base class
* The CLI ``-h|--help`` option should list all known metric providers
* Metric providers classes should have a documentation string describing CLI options, which would be printed via a help-like option (i.e. ``--metric-provider=ClassName --metric-help``) or else just list and print all of them via something like ``--metric-providers`` or ``--metric-help``.
* The actual hook implementation should happen in get_usage, get_limits and check_thresholds; there should be an option (CLI and on the AwsLimitChecker( ) class) to rescue exceptions from the metric provider and just log them.
* ``runner`` parses all ``--metric-option`` into a dict (key/value); passes to AwsLimitChecker as ``metric_provider`` and ``metric_options`` kwargs.

**Comment by sstarcher** [comment]
@jantman I don't believe prometheus would fit well into that situation - #256

**Comment by jantman** [comment]
This issue is quite old. I'm closing it for now, but feel free to comment or reopen if there's renewed interest in it.
