### ISSUE TITLE
Bug in 0.4.0 - SES

### ISSUE THREAD

**Issue by jantman** [jantman/awslimitchecker#170]
SES only currently supports [three regions](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/regions.html) and throws a connection error if used to connect to any other region.

**Comment by pdecat** [comment]
Hi, I was about to report this issue, you're too fast! ;)

**Comment by jantman** [comment]
@pdecat many apologies for this. My integration tests all run against us-east-1...
