### ISSUE TITLE
add support for resource querying

### ISSUE THREAD

**Issue by afgane** [jantman/awslimitchecker#173]
I'd like to use awslimitchecker within another Python app to retrieve the limit of EC2 instances for a specific instance type. I don't current'y see a way to readily do this because all I can retrieve is a complete list of all instances with descriptive key names, eg:
```
>>> c.get_limits(service='EC2')
{'EC2': {'Elastic IP addresses (EIPs)': <awslimitchecker.limit.AwsLimit at 0x106c41cc0>,
  'Rules per VPC security group': <awslimitchecker.limit.AwsLimit at 0x106c412b0>,
  'Running On-Demand EC2 instances': <awslimitchecker.limit.AwsLimit at 0x106c43128>,
  'Running On-Demand c1.medium instances': <awslimitchecker.limit.AwsLimit at 0x106c41b00>,
  ...
```

I feel it should be possible to either filter by resource type within a service (e.g., `c.get_limits(service='EC2', resource='c3.large')` or to have the return list have the resource as the dict key so they can be easily filtered. For example:
```
>>> c.get_limits(service='EC2')
...
'c1.medium': <awslimitchecker.limit.AwsLimit at 0x106c41b00>,
'c1.xlarge': <awslimitchecker.limit.AwsLimit at 0x106c41ba8>
...
```

Or is something like this already possible?

**Comment by jantman** [comment]
@afgane I've done something like this before, but I just looked for the limit on ```Running On-Demand %s instances' % instance_type``.

I agree that this would be nice, but there are a number of inherent problems...

1. If I were to change the names of the limits, existing code for many users would break.
2. The strings that I'm using to describe the limits are the same ones - or very close to those - used by Trusted Advisor, and by the APIs.
3. AWS's limits are really a lot less programmatic and structured than you'd originally think. There's no programmatic connection between a resource type and a limit. Some limits have names that make the connection clear, but there's no API or data element saying that "Running On-Demand c1.medium instances" is the limit of c1.medium's. In most services - certainly EC2 - from a customer perspective limits are an arbitrary key/value pair.

If you'd like a better example of this, take a peek at the Trusted Advisor Service Limits check, which returns some string limit names (which may or may not be the same as the limit name used by the service itself), along with a limit number and a usage number.

The people at AWS aren't even that clear on how all this works. There are a number of times I've opened support tickets asking for clarification on how a given limit is calculated, and had to wait a week to get a reply from someone on the service's development team, because nobody else knew.

__All that being said,__ there's a pretty simple solution to this... the EC2 instance limits all use formulaic names. Getting the dict that you want is as easy as (note I've truncated the long lines in this example):

```python
>>> c = AwsLimitChecker()
awslimitchecker 0.4.1@0.4.1 is AGPL-licensed free software; all users have a right to the full source code of this version. See <git@github.com:jantman/awslimitchecker.git>
>>> x = c.get_limits(service='EC2')
>>> x
{'EC2': {'Running On-Demand r3.xlarge instances': <awslimitchecker.limit.AwsLimit object at 0x7f86b79c3810>, 'Running On-Demand m3.xlarge instances': <awslimitchecker.limit.AwsLimit object at 0x7f86b79c34d0>, (truncated)
>>> res = {}
>>> import re
>>> for k, v in x['EC2'].items():
...     m = re.match(r'^Running On-Demand (\S+) instances', k)
...     if not m:
...         continue
...     res[m.group(1)] = v
... 
>>> res
{'m3.large': <awslimitchecker.limit.AwsLimit object at 0x7f86b79c3490>, 'd2.2xlarge': <awslimitchecker.limit.AwsLimit object at 0x7f86b79c3f10>, 'g2.8xlarge': <awslimitchecker.limit.AwsLimit object at 0x7f86b79ce050>, 'm3.2xlarge': <awslimitchecker.limit.AwsLimit object at 0x7f86b79c3510>, 'r3.4xlarge': <awslimitchecker.limit.AwsLimit object at 0x7f86b79c3890>, (truncated)
```

__Also__, I'm not sure what other python app you're going to be using this in, but please be aware of the licensing requirements around awslimitchecker.

**Comment by afgane** [comment]
Thanks for a detailed answer - parsing a response could certainly be made work, I was wondering I had missed something.
However, having looked at the license, I'm afraid we won't be able to use the library after all ([we're MIT licensed](https://github.com/galaxyproject/cloudman)).
