### ISSUE TITLE
Call to vpc_addresses.all() fails in ec2.py

### ISSUE THREAD

**Issue by drandyziegler** [jantman/awslimitchecker#192]
### Version

0.4.4

### Installation Method

pip install awslimitchecker

### Supporting Software Versions

python --version
2.7.6
virtualenv --version
1.11.4

### Actual Output

awslimitchecker -r us-west-2 -vv -S EC2 -u
awslimitchecker 0.4.4 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
[DEBUG connectable.py:102 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region us-east-1
[INFO connectable.py:120 - awslimitchecker.connectable.connect() ] Connected to support in region us-east-1
[INFO trustedadvisor.py:138 - awslimitchecker.trustedadvisor._poll() ] Beginning TrustedAdvisor poll
[DEBUG trustedadvisor.py:175 - awslimitchecker.trustedadvisor._get_limit_check_id() ] Querying Trusted Advisor checks
[WARNING trustedadvisor.py:184 - awslimitchecker.trustedadvisor._get_limit_check_id() ] Cannot check TrustedAdvisor: AWS Premium Support Subscription is required to use this service.
[INFO trustedadvisor.py:141 - awslimitchecker.trustedadvisor._poll() ] TrustedAdvisor.have_ta is False; not polling TA
[DEBUG trustedadvisor.py:215 - awslimitchecker.trustedadvisor._update_services() ] Updating TA limits on all services
[INFO trustedadvisor.py:231 - awslimitchecker.trustedadvisor._update_services() ] Done updating TA limits on all services
[DEBUG connectable.py:102 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region us-west-2
[INFO connectable.py:120 - awslimitchecker.connectable.connect() ] Connected to ec2 in region us-west-2
[DEBUG connectable.py:102 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region us-west-2
[INFO connectable.py:138 - awslimitchecker.connectable.connect_resource() ] Connected to ec2 (resource) in region us-west-2
[INFO ec2.py:199 - awslimitchecker.services.ec2._update_limits_from_api() ] Querying EC2 DescribeAccountAttributes for limits
[DEBUG ec2.py:216 - awslimitchecker.services.ec2._update_limits_from_api() ] Done setting limits from API
[DEBUG checker.py:219 - awslimitchecker.checker.find_usage() ] Finding usage for service: EC2
[DEBUG ec2.py:62 - awslimitchecker.services.ec2.find_usage() ] Checking usage for service EC2
[DEBUG ec2.py:154 - awslimitchecker.services.ec2._instance_usage() ] Getting usage for on-demand instances
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-04a0383e418563d25 in state stopped
[WARNING ec2.py:159 - awslimitchecker.services.ec2._instance_usage() ] Spot instance found (i-00eda8b3eea1c574c); awslimitchecker does not yet support spot instances.
[WARNING ec2.py:159 - awslimitchecker.services.ec2._instance_usage() ] Spot instance found (i-0a49cac041eb1e35d); awslimitchecker does not yet support spot instances.
[WARNING ec2.py:159 - awslimitchecker.services.ec2._instance_usage() ] Spot instance found (i-06c31f38a08ac8a1d); awslimitchecker does not yet support spot instances.
[WARNING ec2.py:159 - awslimitchecker.services.ec2._instance_usage() ] Spot instance found (i-0a69972806cc74543); awslimitchecker does not yet support spot instances.
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-01be4e9ea9f3d3512 in state stopped
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-042dd47f98ebcd3d4 in state stopped
[WARNING ec2.py:159 - awslimitchecker.services.ec2._instance_usage() ] Spot instance found (i-0e1d4d75b4e39cb27); awslimitchecker does not yet support spot instances.
[WARNING ec2.py:159 - awslimitchecker.services.ec2._instance_usage() ] Spot instance found (i-0b8e7b8e7ef99f22f); awslimitchecker does not yet support spot instances.
[DEBUG ec2.py:163 - awslimitchecker.services.ec2._instance_usage() ] Ignoring instance i-02d60c0b1eef18af0 in state stopped
[WARNING ec2.py:159 - awslimitchecker.services.ec2._instance_usage() ] Spot instance found (i-0c7ee2e51f6962c64); awslimitchecker does not yet support spot instances.
[DEBUG ec2.py:123 - awslimitchecker.services.ec2._get_reserved_instance_count() ] Getting reserved instance information
[DEBUG ec2.py:129 - awslimitchecker.services.ec2._get_reserved_instance_count() ] Skipping ReservedInstance f127bd27-7986-4dc5-9580-dab3e6185e33 with state retired
[DEBUG ec2.py:129 - awslimitchecker.services.ec2._get_reserved_instance_count() ] Skipping ReservedInstance f127bd27-c938-46fa-8d4f-00bb199a8329 with state retired
[DEBUG ec2.py:280 - awslimitchecker.services.ec2._find_usage_networking_sgs() ] Getting usage for EC2 VPC resources
[DEBUG ec2.py:302 - awslimitchecker.services.ec2._find_usage_networking_eips() ] Getting usage for EC2 EIPs
Traceback (most recent call last):
  File "[...]/AmazonTools/aws-helpers/aws/bin/awslimitchecker", line 11, in <module>
    sys.exit(console_entry_point())
  File "[...]/AmazonTools/aws-helpers/aws/local/lib/python2.7/site-packages/awslimitchecker/runner.py", line 357, in console_entry_point
    r.console_entry_point()
  File "[...]/AmazonTools/aws-helpers/aws/local/lib/python2.7/site-packages/awslimitchecker/runner.py", line 347, in console_entry_point
    self.show_usage()
  File "[...]/AmazonTools/aws-helpers/aws/local/lib/python2.7/site-packages/awslimitchecker/runner.py", line 206, in show_usage
    self.checker.find_usage(service=self.service_name)
  File "[...]/AmazonTools/aws-helpers/aws/local/lib/python2.7/site-packages/awslimitchecker/checker.py", line 220, in find_usage
    cls.find_usage()
  File "[...]/AmazonTools/aws-helpers/aws/local/lib/python2.7/site-packages/awslimitchecker/services/ec2.py", line 69, in find_usage
    self._find_usage_networking_eips()
  File "[...]/AmazonTools/aws-helpers/aws/local/lib/python2.7/site-packages/awslimitchecker/services/ec2.py", line 303, in _find_usage_networking_eips
    vpc_addrs = self.resource_conn.vpc_addresses.all()
AttributeError: 'ec2.ServiceResource' object has no attribute 'vpc_addresses'
### Expected Output

It fails to complete.

### Testing Assistance

Happy to run a patch.

Thanks for looking into this.
Regards,
Andy

**Comment by jantman** [comment]
Andy, if it's not too much trouble, could you also confirm your versions of boto3 and botocore ( ``pip freeze | grep boto``)? I've never seen this one before.

Also... is it possible that the account you're using is old enough that it doesn't have VPCs enabled, and only has EC2 Classic (if that's even still possible)?

Either way, I'll start working on a patch.

**Comment by jantman** [comment]
@drandyziegler Andy, I believe that the issue is you're using a version of boto3 that's prior to 1.2.0, and I neglected to specify that dependency explicitly. The VpcAddresses property was only added in boto 1.2.0, as that's the first version that includes the 2015-10-01 EC2 API version.

If you could try upgrading boto3 (``pip install --upgrade boto3``), that should fix the issue. Assuming it does, I'll cut a patch for this.

**Comment by drandyziegler** [comment]
@jantman I'm on boto3 version 1.1.1. Unfortunately my Ubuntu 14.04 does not let me upgrade boto3 in virtualenv.  I have to give it a try on another box with a more recent OS, but I'm sure you found the problem. Thanks for your help.

**Comment by jantman** [comment]
@drandyziegler Hmm... that's really interesting. You should be able to upgrade *anything* in a virtualenv. Perhaps try recreating the virtualenv with ``--no-site-packages`` if the venv was created with an older ``virtualenv`` version (thinking maybe there's a system-wide boto3 that's conflicting)?

I'll leave this open but label it as "Waiting For Response" until you confirm that it's fixed. I may not be able to get the patch out until tomorrow.

**Comment by drandyziegler** [comment]
@jantman It must have used the PYTHONPATH to find a boto3 outside of virtualenv. Fixed this now and EC2 limit checks works using boto3 with version 1.3+.

**Comment by jantman** [comment]
Ok, glad you got it working. I just realized that the [requirement](https://github.com/jantman/awslimitchecker/blob/0.4.4/setup.py#L48) already specifies ``boto3>=1.2.3``, so thanks for closing this.
