### ISSUE TITLE
add support for EC2 placement group limit

### ISSUE THREAD

**Issue by drandyziegler** [jantman/awslimitchecker#199]
## Feature Request

I believe there is a soft limit on placement groups as well which I cannot see in the output of awslimitchecker. Would be nice if this was added since I ran in this limit before.
Thanks.
Andy

**Comment by jantman** [comment]
Andy, do you have a link to any documentation on this limit? I've never heard of it before, and I can't seem to find any reference to it in the [EC2 Service Limits table](http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_ec2) or any other documentation that I've seen.

-Jason

**Comment by drandyziegler** [comment]
So true. They must have removed this limit. I have to admit that it must have been a couple of more years ago that 250 placement groups were a limit and I first had to delete some before I could start new instances. Since then I had my own "janitor" program cleaning these up but it has always been a threat to me to run into this again.
All right. All fine then.
Andy

**Comment by jantman** [comment]
Ok. I'm going to close this. Someone please reopen it if they can find any documentation on this limit.
