### ISSUE TITLE
[Q] refresh trusted advisor check

### ISSUE THREAD

**Issue by lastboy** [jantman/awslimitchecker#203]
Hi,
I have a little question regarding - Trusted Advisor refresh check

For getting an updated results, next refresh should be validated.
See: [refresh-trusted-advisor-check API](http://docs.aws.amazon.com/cli/latest/reference/support/refresh-trusted-advisor-check.html) 
How do you handle that logic today? 

Thank you,
Arik

**Comment by jantman** [comment]
@lastboy That logic isn't handled currently; currently, awslimitchecker simply queries Trusted Advisor. Checks need to be refreshed manually. As far as I can tell, the checks are refreshed weekly by AWS, and more often if you have people looking at TA in the Console.

Keep in mind though, we're only using TA for _limits_, not usage; usage counts are always computed in realtime by limit checker itself. So unless you've requested a limit increase from Support, the TA checks shouldn't change very often.

I'm planning on tackling this within the next week or so. You can take a look at the [0.5.1 milestone](https://github.com/jantman/awslimitchecker/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.5.1) or more specifically the three TA refresh-related issues, #30, #31 and #32.

At the moment I'm leaning towards the default behavior being, if your account has access to TA, awslimitchecker will trigger an update of the check and wait for the update to complete. I'll add options for those issues I linked above (#30, #31 and #32), specifically (1) don't update at all, (2) don't wait for the update to finish, and (3) don't update if the check is less than X hours old.

-Jason

**Comment by lastboy** [comment]
@jantman ... Sweet
I didn't realize that until I read the following line: " usage counts are always computed in realtime by limit checker itself". How did I miss that one :)
I dig into your code and now I can see what you're really doing and that is cool.

One question though. How accurate is the realtime computed usage?

**Comment by jantman** [comment]
@lastboy As far as I know, it's as accurate as it can be. I suppose that if resources change (add or delete) in the middle of a query, it can cause problems. But it queries them when the program runs... i.e. for EC2 On-Demand instances, it calls the EC2 DescribeInstances API, and iterates through every instance, only counting the ones that are running or stopped (i.e. not terminated, not spot instance, not reserved).

At least for the services that haven't been added recently, I haven't identified any issues in accuracy.

**Comment by lastboy** [comment]
@jantman one more thing regarding refreshing the data.
Since awslimitchecker has it's own API calls, what is the overhead and what is a reasonable checker calls should be? (e.g. Every 5 minutes)

**Comment by jantman** [comment]
@lastboy I'm not sure I understand what you're asking. Can you be a bit more specific?

If you're asking how often awslimitchecker should be run:

Everywhere I've used awslimitchecker, we've run it daily via a scheduled job sometime in the early morning.

There's no real generic answer to how often it should be run. The default warning threshold is when usage reaches 80% of a limit, but this can be overridden either globally or per-limit. My current employer has a pretty big AWS infrastructure, so the odds of us adding enough of any resource to bring us from below the 80% threshold, to the point where we'd have a problem, in one day are pretty slim.

**Comment by lastboy** [comment]
What I meant is that awslimitchecker itself uses AWS API for getting the information. What is its overhead in terms of AWS API usage if any.

**Comment by jantman** [comment]
How do you mean "overhead"? Are you asking for the number of API calls, in terms of how they count against your account's API request limit, or the time overhead in terms of how long it takes to run?

**Comment by lastboy** [comment]
I'm asking about: The number of API calls, in terms of how they count against your account's API request limit.

**Comment by jantman** [comment]
It's certainly not going to push an account over the limit on its own.

There's really no way to quantify an answer to your question:
(1) api request rate limits (keep in mind it's a _rate_ limit) vary by size of account
(2) the number of requests varies by the number of resources

If you want to take the time to trace through the code, you can certainly count the number of API calls that are made in the simplest case (an account with NO resources). However most of the API responses are paginated. i.e. ``ec2:DescribeInstances``, by default, returns somewhere around 100 results, and you need to paginate the result. If you have 10 instances, it's 1 API call. If you have 2,000 instances, it's 20 API calls.

Unless you're regularly running up against API rate limiting on your account, I wouldn't be concerned about it. If you are, you should probably run ``awslimitchecker`` off-hours, or else just deal with rate limits being hit.

If you're really interested, you can run it using an isolated IAM user and record the CloudWatch logs, or you can comment out the boto log suppression and count up the total calls.

The short answer is: not a lot. It uses the minimum calls required to get the information it needs.

Furthermore, if you're concerned about limiting it, you could run one service at a time, i.e. see the [help for -S to run only one service](https://awslimitchecker.readthedocs.io/en/latest/cli_usage.html) and [-s to list supported services](https://awslimitchecker.readthedocs.io/en/latest/cli_usage.html#listing-supported-services). Put together, you could do something like:

```bash
for service in $(awslimitchecker -s)
do
    echo "Checking service $service"
    awslimitchecker -S $service
    sleep 60  # sleep 60s between services
done
```

**Comment by lastboy** [comment]
You helped me a lot! 
Thank you very much :)

**Comment by jantman** [comment]
Any time! If you think this issue is resolved, I'll close it for now.

**Comment by lastboy** [comment]
Np thanx
