### ISSUE TITLE
Support AWS CLI --profile switch as pass-through switch

### ISSUE THREAD

**Issue by jimmyraywv** [jantman/awslimitchecker#213]
Right now, with version 0.5.1, users cannot use --profile like they can with aws cli commands.  I would like to see --profile supported as it is used in aws cli and Cloud Custodian (https://github.com/capitalone/cloud-custodian).

When users try to use --profile now, they are presented the "usage" text.

**Comment by jantman** [comment]
Correct, ``--profile`` isn't a supported option. awslimitchecker does not use aws cli, it uses [boto3](http://boto3.readthedocs.io/en/latest/) to interface with the AWS API.

If you wish to use a profile from your ``~/.aws/credentials`` file, you can do so with the ``AWS_PROFILE`` environment variable, per the [boto credentials documentation](http://boto3.readthedocs.io/en/latest/guide/configuration.html#environment-variable-configuration).

**Comment by jantman** [comment]
I just realized that there was an incomplete and untested implementation of this in PR #188. I guess I should try to pick that up and push it across the finish line to close both of these...

**Comment by jantman** [comment]
This has been released in 0.6.0 and is now live on PyPI
