### ISSUE TITLE
_get_reserved_instance_count() error KeyError: 'AvailabilityZone'

### ISSUE THREAD

**Issue by spstarr** [jantman/awslimitchecker#215]
Our Reserved instances show '-' for Availability Zone, the code crashes when this is unset.

  File "/usr/local/cloud/venv/lib/python2.6/site-packages/awslimitchecker/services/ec2.py", line 203, in _get_reserved_instance_count
    if x['AvailabilityZone'] not in az_to_res:
KeyError: 'AvailabilityZone'

AWS GUI shows:

Availability Zone -

**Comment by jantman** [comment]
@spstarr apologies for taking so long to reply.

This appears to be a side-effect of the new "Regional Benefit" [announced last month](https://aws.amazon.com/blogs/aws/ec2-reserved-instance-update-convertible-ris-and-regional-benefit/):

> Starting today, you can choose to waive the capacity reservation associated with Standard RI, run your instance in any AZ in the Region, and have your RI discount automatically applied.

So from what I can tell, the gist of it is that if a Reservation does not have an AvailabilityZone set on it, the capacity of that reservation is effectively subtracted from the sum of all matching On-Demand instances across _all_ AZs.

**Comment by jantman** [comment]
Sorry... that last comment doesn't make sense after further reading of the docs. The new "Regional Benefit" allows Reservations to be set without an associated AZ, in which case the _pricing_ is changed. However, from what I can tell, since this doesn't carry a capacity guarantee, it shouldn't affect the On-Demand Instances limits... i.e. I'm pretty sure these reservations don't change the instance usage calculations for on-demand. Is there any chance you can confirm or deny that?

Either way, I'll cut a fix now so awslimitchecker won't die on AZ-less reservations... but for the time being, they won't be subtracted from On-Demand usage, until I get clarification.

**Comment by jantman** [comment]
@spstarr I merged a fix for the KeyError into the ``develop`` branch in #219; if you could confirm that it fixes the KeyError, that would be great. It should log some information at debug level (run with ``-vv``) every time it finds one of these AZ-less Reservations. I'm interested to know if anyone can figure out if these count against the On-Demand Instances limit or not...

**Comment by spstarr** [comment]
@jantman I will do so this week, thanks!

**Comment by spstarr** [comment]
@jantman I don't see any limits for reserved instances now, it only shows On-Demand for all instances. We should subtract the number of On-demand instances from Reserved?

EC2/Running On-Demand EC2 instances                    52
EC2/Running On-Demand t2.medium instances              19
EC2/Running On-Demand t2.micro instances               2
EC2/Running On-Demand t2.small instances               31

We have 16 t2.medium instances and 29 t2.small instances as Reserved Instances.
So it should be 3 On-demand t2.medium and 2 t2.small instnaces as On-demand?

**Comment by jantman** [comment]
@spstarr that's what I'm not clear about. The announcement about the new AZ-less "Regional Benefit" Reserved Instances didn't say anything about limits.

Is there any chance that you have access to Trusted Advisor, and can refresh the Service Limits check and tell me what it says for these? If not, I can try and put in a support request to find out, but that usually takes a few days to a week...

**Comment by spstarr** [comment]
@jantman sadly I don't have Trusted Advisor on our AWS account, so I can't get that info for you :(

WARNING:awslimitchecker.trustedadvisor:Cannot check TrustedAdvisor: AWS Premium Support Subscription is required to use this service.

**Comment by jantman** [comment]
:( ok, sorry. I'll see if I can reach out to someone from AWS about this...

**Comment by jantman** [comment]
@spstarr Ok, I heard back from AWS this morning.

> From Your last response I understand that You would like to know if the new regional benefit Reserved Instance model will affect Your EC2 service limits, in terms of Instances You can launch within a region.
>
> This is correct, even though the regional benefit model does not guarantee capacity within an availability zone like the standard Reserved instances model, it still will not affect your limits. The limits as indicated on Your ec2 limits page applies to on-demand instances or instances not falling within any reserved instances parameters.

So assuming that's right, it confirms that these Regional Benefit instances should be counted like the other RIs, and subtracted from the total number of running instances to find the On-Demand Instances usage.

I'll try to get a code change for this in the next few days, but I've been unable to commit a whole lot of time to this project lately. I'll do my best...

**Comment by jantman** [comment]
Fix was merged to develop in https://github.com/jantman/awslimitchecker/pull/223

**Comment by spstarr** [comment]
@jantman I've merged your patch into our install, one question though,

it shows:

EC2/Running On-Demand EC2 instances                    20
EC2/Running On-Demand c1.medium instances              0
EC2/Running On-Demand c1.xlarge instances              0
EC2/Running On-Demand c3.2xlarge instances             0
EC2/Running On-Demand c3.4xlarge instances             0
EC2/Running On-Demand c3.8xlarge instances             0
EC2/Running On-Demand c3.large instances               0
EC2/Running On-Demand c3.xlarge instances              0
EC2/Running On-Demand c4.2xlarge instances             0
EC2/Running On-Demand c4.4xlarge instances             0
EC2/Running On-Demand c4.8xlarge instances             0
EC2/Running On-Demand c4.large instances               0
EC2/Running On-Demand c4.xlarge instances              0
EC2/Running On-Demand cc2.8xlarge instances            0
EC2/Running On-Demand cg1.4xlarge instances            0
EC2/Running On-Demand cr1.8xlarge instances            0
EC2/Running On-Demand d2.2xlarge instances             0
EC2/Running On-Demand d2.4xlarge instances             0
EC2/Running On-Demand d2.8xlarge instances             0
EC2/Running On-Demand d2.xlarge instances              0
EC2/Running On-Demand g2.2xlarge instances             0
EC2/Running On-Demand g2.8xlarge instances             0
EC2/Running On-Demand hi1.4xlarge instances            0
EC2/Running On-Demand hs1.8xlarge instances            0
EC2/Running On-Demand i2.2xlarge instances             0
EC2/Running On-Demand i2.4xlarge instances             0
EC2/Running On-Demand i2.8xlarge instances             0
EC2/Running On-Demand i2.xlarge instances              0
EC2/Running On-Demand m1.large instances               0
EC2/Running On-Demand m1.medium instances              0
EC2/Running On-Demand m1.small instances               0
EC2/Running On-Demand m1.xlarge instances              0
EC2/Running On-Demand m2.2xlarge instances             0
EC2/Running On-Demand m2.4xlarge instances             0
EC2/Running On-Demand m2.xlarge instances              0
EC2/Running On-Demand m3.2xlarge instances             0
EC2/Running On-Demand m3.large instances               0
EC2/Running On-Demand m3.medium instances              0
EC2/Running On-Demand m3.xlarge instances              0
EC2/Running On-Demand m4.10xlarge instances            0
EC2/Running On-Demand m4.2xlarge instances             0
EC2/Running On-Demand m4.4xlarge instances             0
EC2/Running On-Demand m4.large instances               0
EC2/Running On-Demand m4.xlarge instances              0
EC2/Running On-Demand r3.2xlarge instances             0
EC2/Running On-Demand r3.4xlarge instances             0
EC2/Running On-Demand r3.8xlarge instances             0
EC2/Running On-Demand r3.large instances               0
EC2/Running On-Demand r3.xlarge instances              0
EC2/Running On-Demand t1.micro instances               0
EC2/Running On-Demand t2.large instances               0
EC2/Running On-Demand t2.medium instances              7
EC2/Running On-Demand t2.micro instances               2
EC2/Running On-Demand t2.nano instances                0
EC2/Running On-Demand t2.small instances               11

But I don't see the list of Reserved <type> instances being shown?

**Comment by jantman** [comment]
@spstarr Since awslimitchecker doesn't yet know anything about Reserved Instance Limits (which as far as I can tell, is just the "Reserved Instance Purchases per Month" limit), reserved instances aren't included in the explicit output - because they don't count against the limits. If you run with ``-vv`` (debug-level output) you should see a message logged for them, but they're not in the actual output. The numbers your see above are on-demand, with reserved subtracted from them. If you need the raw reservation information, I would recommend calling [awslimitchecker.services.ec2._Ec2Service._get_reserved_instance_count()](http://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.services.ec2.html#awslimitchecker.services.ec2._Ec2Service._get_reserved_instance_count) directly, but be aware that it's a private method and its API may not be stable over time.

What does this Nagios plugin do that ``awslimitchecker`` doesn't? The ``awslimitchecker`` command already exits 2 on critical, 1 on warning, or 0 on no issues.

Also, please keep the licensing terms in mind if you're wrapping awslimitchecker in any additional scripting.

**Comment by spstarr** [comment]
Oh just a shell script wrapper, not changing awslimitchecker

**Comment by jantman** [comment]
Ok. If you're including the output from awslimitchecker, it would be preferred (I suppose something like a nagios check is a bit of a gray area, so I can't say "required") to also include the license notice and source code URL.

**Comment by jantman** [comment]
This has been released in 0.6.0 and is now live on PyPI
