### ISSUE TITLE
Add support for p2 instances

### ISSUE THREAD

**Issue by jleader** [jantman/awslimitchecker#217]
We recently started a project using a p2.xlarge instance, as a result we get:

  ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'p2.xlarge'; not counting

There are also p2.8xlarge and p2.16xlarge instances available, according to https://aws.amazon.com/ec2/instance-types/p2/ and https://aws.amazon.com/ec2/instance-types/#p2. Apparently these are intended for general GPU use for parallel computation, where the g2 types are more specifically for graphics-intensive uses.

**Comment by jantman** [comment]
Apologies for this; I was completely unaware that there are new instance types.

I should have a fix for this done tonight in a branch, and hoping for a release within the next week.

**Comment by jantman** [comment]
@jleader this was merged to the "develop" branch in #218 ; I expect to cut a release within a week or so, but if you need it before then, you can install directly from develop.
