### ISSUE TITLE
Default ElastiCache/Nodes Limit Increase

### ISSUE THREAD

**Issue by bflad** [jantman/awslimitchecker#241]
## Feature Request

It appears Amazon increased the default limit for number of Elasticache nodes per region at some point since the service was added here (from 50 to 100).

* Current: http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_elasticache
* Earlier this year: https://web.archive.org/web/20160113103216/http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html

### Feature Description

I can submit the trivial PR. Update the default limit from 50 to 100:
* https://github.com/jantman/awslimitchecker/blob/develop/awslimitchecker/services/elasticache.py#L172

### Use Cases

More accurate reporting of `ElastiCache/Nodes` limits for those of us over the current 50 limit.

### Testing Assistance

Absolutely.

**Comment by jantman** [comment]
This was fixed in #242 - thanks *so* much for the pull request!

I'm not sure yet when the next release will be cut, but this will be included in it.

**Comment by jantman** [comment]
This has been released in 0.7.0 and is live on pypi.
