### ISSUE TITLE
Add r4 instance types

### ISSUE THREAD

**Issue by jleader** [jantman/awslimitchecker#244]
### Feature Description

Add support for r4 instance types (https://aws.amazon.com/blogs/aws/new-next-generation-r4-memory-optimized-ec2-instances/)

### Use Cases

Be able to report usage and check limits for the 6 new memory-optimized instance types.

### Testing Assistance

I'd be happy to assist with testing, but one of our teams was just experimenting with an r4 instance, they may have deleted it by now.

**Comment by jantman** [comment]
@jleader This was done in #231, which is merged to develop and should be in the next release (0.7.0). That will go out once I'm done reviewing and verifying #243, which should be soon (hopefully in the next few days).
