### ISSUE TITLE
Make 0.8.0 1.0.0?

### ISSUE THREAD

**Issue by jantman** [jantman/awslimitchecker#252]
Is it time for 1.0.0???

**Comment by jmcarp** [comment]
In the meantime, do you have time to cut 0.7.1?

**Comment by jantman** [comment]
I'm quite busy in my personal life, but I'll make an attempt to do something this week...

**Comment by jmcarp** [comment]
Sorry, not a big deal, I was just trying to suggest something that would take less time than a new major/minor release. I was hoping that cutting 0.7.1 would be as lightweight as bumping the version in the code and running something like

```
python setup.py register sdist bdist_wheel
twine upload dist/*
```

Anyway, thanks for the great work on this project!

**Comment by jantman** [comment]
@jmcarp Unfortunately I stage releases from the develop branch, and I've already got most of 0.8.0 staged there... I'm spending the afternoon today trying to get 0.8.0 out so I don't have to feel bad about it sitting any longer. Apologies for the delay.

**Comment by jantman** [comment]
I'm cutting 0.8.0 today.
