### ISSUE TITLE
Getting incorrect limit value

### ISSUE THREAD

**Issue by alinahazan** [jantman/awslimitchecker#266]
### Use Cases

I'm using the awslimitchecker to get usages and limits of the AWS services in
all regions. 
In some cases, the value of the limit is not correct. 

For example:

From the script:
region=mumbai
EC2 'Running On-Demand r3.2xlarge instances': 1 (limit=20)

From the UI of limits in AWS console:
The limit is 500.

### Version

awslimitchecker 0.6.0 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
awslimitchecker 0.6.0 (see <https://github.com/jantman/awslimitchecker> for source code)

### Installation Method

Not using virtual env

### Supporting Software Versions

Python 2.7.6

### Actual Output

the script I run:
import logging
logging.basicConfig()
logger = logging.getLogger()
import pprint
import sys

import argparse

parser = argparse.ArgumentParser(description='Process some integers.')
parser.add_argument("-r", "--region", dest="myRegionVariable", help="region?", metavar="REGION")

args = parser.parse_args()

from awslimitchecker.checker import AwsLimitChecker
checker = AwsLimitChecker(region=args.myRegionVariable)
checker.find_usage()

for service, svc_limits in sorted(checker.get_limits().items()):
    for limit_name, limit in sorted(svc_limits.items()):
        if 'Firehose' not in service:
            print("{service} '{limit_name}': {u} (limit={l})".format(
                service=service,
                limit_name=limit_name,
                u=limit.get_current_usage_str(),
                l=limit.get_limit()
            ))
        else:
            continue

the output:
awslimitchecker 0.6.0 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
WARNING:awslimitchecker.services.ses:Skipping SES: Could not connect to the endpoint URL: "https://email.ap-south-1.amazonaws.com/"
WARNING:awslimitchecker.services.ses:Skipping SES: Could not connect to the endpoint URL: "https://email.ap-south-1.amazonaws.com/"
WARNING:awslimitchecker.services.ec2:EC2 spot instance support is experimental and results may not me accurate in all cases. Please see the notes at: <http://awslimitchecker.readthedocs.io/en/latest/limits.html#ec2>
ERROR:awslimitchecker.services.firehose:Caught exception when trying to use Firehose; perhaps the Firehose service is not available in this region?
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awslimitchecker/services/firehose.py", line 66, in find_usage
    self._find_delivery_streams()
  File "/usr/local/lib/python2.7/dist-packages/awslimitchecker/services/firehose.py", line 78, in _find_delivery_streams
    streams = self.conn.list_delivery_streams()
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 530, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 170, in _send_request
    success_response, exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
EndpointConnectionError: Could not connect to the endpoint URL: "https://firehose.ap-south-1.amazonaws.com/"
WARNING:awslimitchecker.services.ses:Skipping SES: Could not connect to the endpoint URL: "https://email.ap-south-1.amazonaws.com/"
AutoScaling 'Auto Scaling groups': 0 (limit=20)
AutoScaling 'Launch configurations': 0 (limit=100)
CloudFormation 'Stacks': 0 (limit=200)
EBS 'Active snapshots': 50 (limit=10000)
EBS 'Active volumes': 4 (limit=5000)
EBS 'Cold (HDD) volume storage (GiB)': 0 (limit=20480)
EBS 'General Purpose (SSD) volume storage (GiB)': 255 (limit=614400)
EBS 'Magnetic volume storage (GiB)': 8 (limit=20480)
EBS 'Provisioned IOPS': 0 (limit=40000)
EBS 'Provisioned IOPS (SSD) storage (GiB)': 0 (limit=20480)
EBS 'Throughput Optimized (HDD) volume storage (GiB)': 0 (limit=20480)
EC2 'Elastic IP addresses (EIPs)': 0 (limit=5)
EC2 'Max active spot fleets per region': 0 (limit=1000)
EC2 'Max launch specifications per spot fleet': <unknown> (limit=50)
EC2 'Max spot instance requests per region': 0 (limit=20)
EC2 'Max target capacity for all spot fleets in region': 0 (limit=5000)
EC2 'Max target capacity per spot fleet': <unknown> (limit=3000)
EC2 'Rules per VPC security group': sg-e4a62c8d=1 (limit=50)
EC2 'Running On-Demand EC2 instances': 1 (limit=4000)
EC2 'Running On-Demand c1.medium instances': 0 (limit=20)
EC2 'Running On-Demand c1.xlarge instances': 0 (limit=20)
EC2 'Running On-Demand c3.2xlarge instances': 0 (limit=20)
EC2 'Running On-Demand c3.4xlarge instances': 0 (limit=20)
EC2 'Running On-Demand c3.8xlarge instances': 0 (limit=20)
EC2 'Running On-Demand c3.large instances': 0 (limit=20)
EC2 'Running On-Demand c3.xlarge instances': 0 (limit=20)
EC2 'Running On-Demand c4.2xlarge instances': 0 (limit=20)
EC2 'Running On-Demand c4.4xlarge instances': 0 (limit=10)
EC2 'Running On-Demand c4.8xlarge instances': 0 (limit=5)
EC2 'Running On-Demand c4.large instances': 0 (limit=20)
EC2 'Running On-Demand c4.xlarge instances': 0 (limit=20)
EC2 'Running On-Demand cc2.8xlarge instances': 0 (limit=20)
EC2 'Running On-Demand cg1.4xlarge instances': 0 (limit=2)
EC2 'Running On-Demand cr1.8xlarge instances': 0 (limit=2)
EC2 'Running On-Demand d2.2xlarge instances': 0 (limit=20)
EC2 'Running On-Demand d2.4xlarge instances': 0 (limit=10)
EC2 'Running On-Demand d2.8xlarge instances': 0 (limit=5)
EC2 'Running On-Demand d2.xlarge instances': 0 (limit=20)
EC2 'Running On-Demand g2.2xlarge instances': 0 (limit=5)
EC2 'Running On-Demand g2.8xlarge instances': 0 (limit=2)
EC2 'Running On-Demand hi1.4xlarge instances': 0 (limit=2)
EC2 'Running On-Demand hs1.8xlarge instances': 0 (limit=2)
EC2 'Running On-Demand i2.2xlarge instances': 0 (limit=8)
EC2 'Running On-Demand i2.4xlarge instances': 0 (limit=4)
EC2 'Running On-Demand i2.8xlarge instances': 0 (limit=2)
EC2 'Running On-Demand i2.xlarge instances': 0 (limit=8)
EC2 'Running On-Demand m1.large instances': 0 (limit=20)
EC2 'Running On-Demand m1.medium instances': 0 (limit=20)
EC2 'Running On-Demand m1.small instances': 0 (limit=20)
EC2 'Running On-Demand m1.xlarge instances': 0 (limit=20)
EC2 'Running On-Demand m2.2xlarge instances': 0 (limit=20)
EC2 'Running On-Demand m2.4xlarge instances': 0 (limit=20)
EC2 'Running On-Demand m2.xlarge instances': 0 (limit=20)
EC2 'Running On-Demand m3.2xlarge instances': 0 (limit=20)
EC2 'Running On-Demand m3.large instances': 0 (limit=20)
EC2 'Running On-Demand m3.medium instances': 0 (limit=20)
EC2 'Running On-Demand m3.xlarge instances': 0 (limit=20)
EC2 'Running On-Demand m4.10xlarge instances': 0 (limit=5)
EC2 'Running On-Demand m4.16xlarge instances': 0 (limit=5)
EC2 'Running On-Demand m4.2xlarge instances': 0 (limit=20)
EC2 'Running On-Demand m4.4xlarge instances': 0 (limit=10)
EC2 'Running On-Demand m4.large instances': 0 (limit=20)
EC2 'Running On-Demand m4.xlarge instances': 0 (limit=20)
EC2 'Running On-Demand p2.16xlarge instances': 0 (limit=1)
EC2 'Running On-Demand p2.8xlarge instances': 0 (limit=1)
EC2 'Running On-Demand p2.xlarge instances': 0 (limit=1)
EC2 'Running On-Demand r3.2xlarge instances': 1 (limit=20)
EC2 'Running On-Demand r3.4xlarge instances': 0 (limit=10)
EC2 'Running On-Demand r3.8xlarge instances': 0 (limit=5)
EC2 'Running On-Demand r3.large instances': 0 (limit=20)
EC2 'Running On-Demand r3.xlarge instances': 0 (limit=20)
EC2 'Running On-Demand t1.micro instances': 0 (limit=20)
EC2 'Running On-Demand t2.large instances': 0 (limit=20)
EC2 'Running On-Demand t2.medium instances': 0 (limit=20)
EC2 'Running On-Demand t2.micro instances': 0 (limit=20)
EC2 'Running On-Demand t2.nano instances': 0 (limit=20)
EC2 'Running On-Demand t2.small instances': 0 (limit=20)
EC2 'Running On-Demand x1.16xlarge instances': 0 (limit=20)
EC2 'Running On-Demand x1.32xlarge instances': 0 (limit=20)
EC2 'Security groups per VPC': vpc-5753f13e=1 (limit=500)
EC2 'VPC Elastic IP addresses (EIPs)': 0 (limit=2000)
EC2 'VPC security groups per elastic network interface': max: eni-0f9e1843=1 (eni-0f9e1843=1, eni-d8392895=1, eni-679e182b=1, eni-8f9315c3=1, eni-1337265e=1, eni-e19e18ad=1) (limit=5)
ELB 'Active load balancers': 0 (limit=20)
ELB 'Listeners per load balancer': <unknown> (limit=100)
ElastiCache 'Clusters': 0 (limit=50)
ElastiCache 'Nodes': 0 (limit=50)
ElastiCache 'Nodes per Cluster': <unknown> (limit=20)
ElastiCache 'Parameter Groups': 4 (limit=20)
ElastiCache 'Security Groups': 0 (limit=50)
ElastiCache 'Subnet Groups': 0 (limit=50)
ElasticBeanstalk 'Application versions': 0 (limit=500)
ElasticBeanstalk 'Applications': 0 (limit=25)
ElasticBeanstalk 'Environments': 0 (limit=200)
IAM 'Groups': max: 5 (5, 5) (limit=100)
IAM 'Instance profiles': max: 1 (1, 1) (limit=100)
IAM 'Policies': max: 2 (2, 2) (limit=1000)
IAM 'Policy Versions In Use': max: 9 (9, 9) (limit=10000)
IAM 'Roles': max: 1 (1, 1) (limit=250)
IAM 'Server certificates': max: 0 (0, 0) (limit=20)
IAM 'Users': max: 37 (37, 37) (limit=5000)
RDS 'DB Cluster Parameter Groups': 0 (limit=20)
RDS 'DB Clusters': 0 (limit=40)
RDS 'DB instances': 0 (limit=20)
RDS 'DB parameter groups': 0 (limit=20)
RDS 'DB security groups': 0 (limit=20)
RDS 'DB snapshots per user': 0 (limit=100)
RDS 'Event Subscriptions': 0 (limit=20)
RDS 'Max auths per security group': default=0 (limit=20)
RDS 'Option Groups': 0 (limit=20)
RDS 'Read replicas per master': 0 (limit=5)
RDS 'Reserved Instances': 0 (limit=20)
RDS 'Storage quota (GB)': 0 (limit=100000)
RDS 'Subnet Groups': 0 (limit=20)
RDS 'Subnets per Subnet Group': 0 (limit=20)
RDS 'VPC Security Groups': 0 (limit=5)
S3 'Buckets': 61 (limit=100)
SES 'Daily sending quota': <unknown> (limit=200)
VPC 'Entries per route table': rtb-29872f40=2 (limit=50)
VPC 'Internet gateways': 1 (limit=100)
VPC 'NAT Gateways per AZ': <unknown> (limit=5)
VPC 'Network ACLs per VPC': vpc-5753f13e=1 (limit=200)
VPC 'Route tables per VPC': vpc-5753f13e=1 (limit=200)
VPC 'Rules per network ACL': acl-8105ace8=4 (limit=20)
VPC 'Subnets per VPC': vpc-5753f13e=2 (limit=200)
VPC 'VPCs': 1 (limit=100)

### Expected Output

For example:
EC2 'Running On-Demand r3.2xlarge instances': 1 (limit=500)
EC2 'Running On-Demand r3.4xlarge instances': 0 (limit=500)
EC2 'Running On-Demand r3.8xlarge instances': 0 (limit=500)
EC2 'Running On-Demand r3.large instances': 0 (limit=500)

### TrustedAdvisor

Business Support Plan

### Testing Assistance

I will be able to assist in testing pre-release code for the feature.

**Comment by jantman** [comment]
@alinahazan, thank you for the detailed issue report.

1. I'll probably need to see the debug-level output to know what's going on here, specifically the output related to Trusted Advisor. The easiest way to get that would probably be to just run ``awslimitchecker -r REGION_NAME -l -vv`` directly and post the output.
2. When was the last time you refreshed the Trusted Advisor checks through the AWS Consule? Support for doing that through awslimitchecker was only introduced in [0.7.0](https://github.com/jantman/awslimitchecker/blob/master/CHANGES.rst#070-2017-01-15), and it appears your wrapper script is not making use of that.
3. Can you please tell me what region you're seeing this problem in?

As per the [documentation on supported EC2 limits](http://awslimitchecker.readthedocs.io/en/latest/limits.html#ec2), the ``Running On-Demand r3.2xlarge instances`` limit is one of the many limits that are not currently exposed via an EC2 API; they can either be retrieved via Trusted Advisor, or need to be manually specified. 20 is the default value.

I can think of a few reasons why you might be seeing this behavior:

1. Trusted Advisor isn't really active for your account.
2. Trusted Advisor isn't reporting on that limit for that region. I'm not sure if TA supports all limits in all regions or not...
3. Your Trusted Advisor Service Limits check is stale. You can either use the command line or [python options](http://awslimitchecker.readthedocs.io/en/latest/python_usage.html#refreshing-trusted-advisor-check-results) to refresh it using awslimitchecker >= 0.7.0 (see the [docs section on Trusted Advisor](http://awslimitchecker.readthedocs.io/en/latest/internals.html#trusted-advisor)), or you can log in to the AWS Console and view the Trusted Advisor -> Performance -> Service Limits check manually; viewing it should cause it to refresh.

If it's not possible to get the updated limit value via Trusted Advisor, then your only option is to specify your limit value manually as a [Limit Override](http://awslimitchecker.readthedocs.io/en/latest/internals.html#limit-value-precedence). For command-line usage, see [Overriding Limits](http://awslimitchecker.readthedocs.io/en/latest/cli_usage.html#overriding-limits). For Python usage, see [Setting a Limit Override](http://awslimitchecker.readthedocs.io/en/latest/python_usage.html#setting-a-limit-override), as well as the AwsLimitChecker class's [set_limit_override()](http://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.checker.html#awslimitchecker.checker.AwsLimitChecker.set_limit_override) and [set_limit_overrides()](http://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.checker.html#awslimitchecker.checker.AwsLimitChecker.set_limit_overrides) methods. There is a more detailed example of how to set limit and threshold overrides from Python in the [Full Jenkins Example](https://github.com/jantman/awslimitchecker/blob/master/docs/examples/check_aws_limits.py).

-Jason

**Comment by alinahazan** [comment]
1. awslimitchecker -r ap-south-1 -l -vv
awslimitchecker 0.6.0 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
[DEBUG connectable.py:121 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region us-east-1
[INFO connectable.py:139 - awslimitchecker.connectable.connect() ] Connected to support in region us-east-1
[INFO trustedadvisor.py:144 - awslimitchecker.trustedadvisor._poll() ] Beginning TrustedAdvisor poll
[DEBUG trustedadvisor.py:197 - awslimitchecker.trustedadvisor._get_limit_check_id() ] Querying Trusted Advisor checks
[DEBUG trustedadvisor.py:217 - awslimitchecker.trustedadvisor._get_limit_check_id() ] Found TA check; id=eW7HH0l7J9
[DEBUG trustedadvisor.py:163 - awslimitchecker.trustedadvisor._poll() ] Got TrustedAdvisor data for check eW7HH0l7J9 as of 2017-03-15 13:37:19+00:00
[INFO trustedadvisor.py:185 - awslimitchecker.trustedadvisor._poll() ] Finished TrustedAdvisor poll
[DEBUG trustedadvisor.py:237 - awslimitchecker.trustedadvisor._update_services() ] Updating TA limits on all services
[INFO trustedadvisor.py:250 - awslimitchecker.trustedadvisor._update_services() ] TrustedAdvisor returned check results for unknown limit 'Reserved Instances - purchase limit (monthly)' (service EC2)
[INFO trustedadvisor.py:257 - awslimitchecker.trustedadvisor._update_services() ] Done updating TA limits on all services
[DEBUG connectable.py:121 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region ap-south-1
[INFO connectable.py:157 - awslimitchecker.connectable.connect_resource() ] Connected to iam (resource) in region aws-global
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AccessKeysPerUserQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AccountAccessKeysPresent
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AccountMFAEnabled
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AccountSigningCertificatesPresent
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AssumeRolePolicySizeQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AttachedPoliciesPerGroupQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AttachedPoliciesPerRoleQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: AttachedPoliciesPerUserQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: GroupPolicySizeQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: GroupsPerUserQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: MFADevices
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: MFADevicesInUse
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: PolicySizeQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: Providers
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: RolePolicySizeQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: SigningCertificatesPerUserQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: UserPolicySizeQuota
[DEBUG iam.py:166 - awslimitchecker.services.iam._update_limits_from_api() ] Ignoring IAM AccountSummary attribute: VersionsPerPolicyQuota
[DEBUG connectable.py:121 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region ap-south-1
[INFO connectable.py:139 - awslimitchecker.connectable.connect() ] Connected to ses in region ap-south-1
[WARNING ses.py:107 - awslimitchecker.services.ses._update_limits_from_api() ] Skipping SES: Could not connect to the endpoint URL: "https://email.ap-south-1.amazonaws.com/"
[DEBUG connectable.py:121 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region ap-south-1
[INFO connectable.py:139 - awslimitchecker.connectable.connect() ] Connected to rds in region ap-south-1
[INFO rds.py:277 - awslimitchecker.services.rds._update_limits_from_api() ] Querying RDS DescribeAccountAttributes for limits
[INFO rds.py:283 - awslimitchecker.services.rds._update_limits_from_api() ] RDS DescribeAccountAttributes returned unknownlimit: DBClusterRoles (max: 5; used: 0)
[DEBUG rds.py:289 - awslimitchecker.services.rds._update_limits_from_api() ] Done setting limits from API.
[DEBUG connectable.py:121 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region ap-south-1
[INFO connectable.py:139 - awslimitchecker.connectable.connect() ] Connected to autoscaling in region ap-south-1
[INFO autoscaling.py:145 - awslimitchecker.services.autoscaling._update_limits_from_api() ] Querying EC2 DescribeAccountAttributes for limits
[DEBUG cloudformation.py:107 - awslimitchecker.services.cloudformation._update_limits_from_api() ] Setting CloudFormation limits from API
[DEBUG connectable.py:121 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region ap-south-1
[INFO connectable.py:139 - awslimitchecker.connectable.connect() ] Connected to cloudformation in region ap-south-1
[DEBUG connectable.py:121 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region ap-south-1
[INFO connectable.py:139 - awslimitchecker.connectable.connect() ] Connected to ec2 in region ap-south-1
[DEBUG connectable.py:121 - awslimitchecker.connectable._boto3_connection_kwargs() ] Connecting to region ap-south-1
[INFO connectable.py:157 - awslimitchecker.connectable.connect_resource() ] Connected to ec2 (resource) in region ap-south-1
[INFO ec2.py:291 - awslimitchecker.services.ec2._update_limits_from_api() ] Querying EC2 DescribeAccountAttributes for limits
[DEBUG ec2.py:308 - awslimitchecker.services.ec2._update_limits_from_api() ] Done setting limits from API
AutoScaling/Auto Scaling groups                        20 (API)
AutoScaling/Launch configurations                      100 (API)
CloudFormation/Stacks                                  200 (API)
EBS/Active snapshots                                   10000 (TA)
EBS/Active volumes                                     5000 (TA)
EBS/Cold (HDD) volume storage (GiB)                    20480
EBS/General Purpose (SSD) volume storage (GiB)         614400 (TA)
EBS/Magnetic volume storage (GiB)                      20480 (TA)
EBS/Provisioned IOPS                                   40000
EBS/Provisioned IOPS (SSD) storage (GiB)               20480
EBS/Throughput Optimized (HDD) volume storage (GiB)    20480
EC2/Elastic IP addresses (EIPs)                        5 (API)
EC2/Max active spot fleets per region                  1000
EC2/Max launch specifications per spot fleet           50
EC2/Max spot instance requests per region              20
EC2/Max target capacity for all spot fleets in region  5000
EC2/Max target capacity per spot fleet                 3000
EC2/Rules per VPC security group                       50
EC2/Running On-Demand EC2 instances                    4000 (API)
EC2/Running On-Demand c1.medium instances              20
EC2/Running On-Demand c1.xlarge instances              20
EC2/Running On-Demand c3.2xlarge instances             20
EC2/Running On-Demand c3.4xlarge instances             20
EC2/Running On-Demand c3.8xlarge instances             20
EC2/Running On-Demand c3.large instances               20
EC2/Running On-Demand c3.xlarge instances              20
EC2/Running On-Demand c4.2xlarge instances             20
EC2/Running On-Demand c4.4xlarge instances             10
EC2/Running On-Demand c4.8xlarge instances             5
EC2/Running On-Demand c4.large instances               20
EC2/Running On-Demand c4.xlarge instances              20
EC2/Running On-Demand cc2.8xlarge instances            20
EC2/Running On-Demand cg1.4xlarge instances            2
EC2/Running On-Demand cr1.8xlarge instances            2
EC2/Running On-Demand d2.2xlarge instances             20
EC2/Running On-Demand d2.4xlarge instances             10
EC2/Running On-Demand d2.8xlarge instances             5
EC2/Running On-Demand d2.xlarge instances              20
EC2/Running On-Demand g2.2xlarge instances             5
EC2/Running On-Demand g2.8xlarge instances             2
EC2/Running On-Demand hi1.4xlarge instances            2
EC2/Running On-Demand hs1.8xlarge instances            2
EC2/Running On-Demand i2.2xlarge instances             8
EC2/Running On-Demand i2.4xlarge instances             4
EC2/Running On-Demand i2.8xlarge instances             2
EC2/Running On-Demand i2.xlarge instances              8
EC2/Running On-Demand m1.large instances               20
EC2/Running On-Demand m1.medium instances              20
EC2/Running On-Demand m1.small instances               20
EC2/Running On-Demand m1.xlarge instances              20
EC2/Running On-Demand m2.2xlarge instances             20
EC2/Running On-Demand m2.4xlarge instances             20
EC2/Running On-Demand m2.xlarge instances              20
EC2/Running On-Demand m3.2xlarge instances             20
EC2/Running On-Demand m3.large instances               20
EC2/Running On-Demand m3.medium instances              20
EC2/Running On-Demand m3.xlarge instances              20
EC2/Running On-Demand m4.10xlarge instances            5
EC2/Running On-Demand m4.16xlarge instances            5
EC2/Running On-Demand m4.2xlarge instances             20
EC2/Running On-Demand m4.4xlarge instances             10
EC2/Running On-Demand m4.large instances               20
EC2/Running On-Demand m4.xlarge instances              20
EC2/Running On-Demand p2.16xlarge instances            1
EC2/Running On-Demand p2.8xlarge instances             1
EC2/Running On-Demand p2.xlarge instances              1
EC2/Running On-Demand r3.2xlarge instances             20
EC2/Running On-Demand r3.4xlarge instances             10
EC2/Running On-Demand r3.8xlarge instances             5
EC2/Running On-Demand r3.large instances               20
EC2/Running On-Demand r3.xlarge instances              20
EC2/Running On-Demand t1.micro instances               20
EC2/Running On-Demand t2.large instances               20
EC2/Running On-Demand t2.medium instances              20
EC2/Running On-Demand t2.micro instances               20
EC2/Running On-Demand t2.nano instances                20
EC2/Running On-Demand t2.small instances               20
EC2/Running On-Demand x1.16xlarge instances            20
EC2/Running On-Demand x1.32xlarge instances            20
EC2/Security groups per VPC                            500
EC2/VPC Elastic IP addresses (EIPs)                    2000 (API)
EC2/VPC security groups per elastic network interface  5 (API)
ELB/Active load balancers                              20
ELB/Listeners per load balancer                        100
ElastiCache/Clusters                                   50
ElastiCache/Nodes                                      50
ElastiCache/Nodes per Cluster                          20
ElastiCache/Parameter Groups                           20
ElastiCache/Security Groups                            50
ElastiCache/Subnet Groups                              50
ElasticBeanstalk/Application versions                  500
ElasticBeanstalk/Applications                          25
ElasticBeanstalk/Environments                          200
Firehose/Delivery streams per region                   20
IAM/Groups                                             100 (API)
IAM/Instance profiles                                  100 (API)
IAM/Policies                                           1000 (API)
IAM/Policy Versions In Use                             10000 (API)
IAM/Roles                                              250 (API)
IAM/Server certificates                                20 (API)
IAM/Users                                              5000 (API)
RDS/DB Cluster Parameter Groups                        20 (API)
RDS/DB Clusters                                        40 (API)
RDS/DB instances                                       20 (API)
RDS/DB parameter groups                                20 (API)
RDS/DB security groups                                 20 (API)
RDS/DB snapshots per user                              100 (API)
RDS/Event Subscriptions                                20 (API)
RDS/Max auths per security group                       20 (API)
RDS/Option Groups                                      20 (API)
RDS/Read replicas per master                           5 (API)
RDS/Reserved Instances                                 20 (API)
RDS/Storage quota (GB)                                 100000 (API)
RDS/Subnet Groups                                      20 (API)
RDS/Subnets per Subnet Group                           20 (API)
RDS/VPC Security Groups                                5
S3/Buckets                                             100
SES/Daily sending quota                                200
VPC/Entries per route table                            50
VPC/Internet gateways                                  100 (TA)
VPC/NAT Gateways per AZ                                5
VPC/Network ACLs per VPC                               200
VPC/Route tables per VPC                               200
VPC/Rules per network ACL                              20
VPC/Subnets per VPC                                    200
VPC/VPCs                                               100 (TA)

2. Refreshed: 2 hours ago 
3. I see the problem in Mumabi

In case i was to upgrade to version 0.7.0 (to avoid refreshing the TA manually always), how can i do it?

**Comment by jantman** [comment]
Thank you for the quick response.

I have not been able to find any AWS documentation to confirm this, but I believe that Trusted Advisor is only reporting EC2 service limits in US regions. Unless your service limits were raised from 20 to 500 in the last 2 hours, that seems to be the only possibility.

Assuming that is the case, unfortunately, your only option will be to manually specify your service limits in an override file or on the command line, as I described in my last comment. My current employer does this for many limits across many regions and accounts, though we have Enterprise support and have opened a feature request to get AWS to expose the rest of the current limits via API. When/if that is ever done, I will add support for it ASAP.

If you do want to upgrade, you would need to install the latest version the same way you installed the version you currently have. If you used pip (``pip install awslimitchecker``), you would just have to re-run that command with the option to upgrade (``pip install --upgrade awslimitchecker``). Once that is done, you can refresh trusted advisor using the pertinent command line arguments; see ``awslimitchecker --help``.

I will leave this issue open for a few days for you the confirm the above, and in case you have any questions.

**Comment by alinahazan** [comment]
Thank YOU for the quick response!
I really appreciate it. 

I also see inconsistence data in limit of Singapore region:

For example, here are the results I got today:

Running_On-Demand_c3.xlarge_instances_limit (the correct limit is 2000)
2017-03-15 17:48:38	
2000
2017-03-15 17:34:08	
20
2017-03-15 17:19:17	
20
2017-03-15 17:03:57	
20
2017-03-15 16:49:01	
20
2017-03-15 16:34:05	
20
2017-03-15 16:19:07	
20
2017-03-15 16:04:15	
20
2017-03-15 15:49:03	
20
2017-03-15 15:34:07	
20
2017-03-15 15:19:03	
20

Running_On-Demand_c3.large_instances_limit (the correct limit is 2000)
**2017-03-15 17:48:38	
20**
2017-03-15 17:34:08	
2000
2017-03-15 17:19:17	
2000
2017-03-15 17:03:57	
2000
2017-03-15 16:49:01	
2000
2017-03-15 16:34:05	
2000
2017-03-15 16:19:07	
2000
2017-03-15 16:04:15	
2000
2017-03-15 15:49:03	
2000
2017-03-15 15:34:07	
2000

Running_On-Demand_m3.xlarge_instances_limit (the correct limit is 2000)
**2017-03-15 17:48:39	
20**
2017-03-15 17:34:10	
2000
2017-03-15 17:19:19	
2000
2017-03-15 17:03:59	
2000
2017-03-15 16:49:03	
2000
2017-03-15 16:34:07	
2000
2017-03-15 16:19:10	
2000
2017-03-15 16:04:17	
2000
2017-03-15 15:49:05	
2000
2017-03-15 15:34:09	
2000
2017-03-15 15:19:06	
2000

Running_On-Demand_m3.2xlarge_instances_limit (the correct limit is 2000)
2017-03-15 17:48:39	
2000
2017-03-15 17:34:10	
20
2017-03-15 17:19:19	
20
2017-03-15 17:03:59	
20
2017-03-15 16:49:03	
20
2017-03-15 16:34:07	
20
2017-03-15 16:19:09	
20
2017-03-15 16:04:17	
20
2017-03-15 15:49:05	
20
2017-03-15 15:34:09	
20
2017-03-15 15:19:05	
20

**Comment by jantman** [comment]
That is **very** strange to me. Perhaps this is some sort of bug in Trusted Advisor itself?

**Comment by alinahazan** [comment]
I opened a ticket to AWS to understand if something is wrong on their side, I'll update here if there will be something interesting.

**Comment by jantman** [comment]
@alinahazan have you heard anything back about this? From what you posted above, I'm inclined to think that it's a bug on the AWS end, not in awslimitchecker.

**Comment by jantman** [comment]
I have not heard back in over a month, so I'm going to close this issue. If you are able to get more information from AWS and it turns out to be a problem with awslimitchecker, please reopen it.

**Comment by alinahazan** [comment]
As I understood from AWS support, they just dont support it, and dont have plans to support it in the future. 
We can extract very minimal information in terms of limits by API.
