### ISSUE TITLE
awslimitchecker failure (expects Firehose ?)

### ISSUE THREAD

**Issue by spetsnaz84** [jantman/awslimitchecker#267]
awslimitchecker --region ap-southeast-2 
awslimitchecker 0.8.0 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
WARNING:awslimitchecker.services.ses:Skipping SES: Could not connect to the endpoint URL: "https://email.ap-southeast-2.amazonaws.com/"
WARNING:awslimitchecker.services.ses:Skipping SES: Could not connect to the endpoint URL: "https://email.ap-southeast-2.amazonaws.com/"
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.large'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.large'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.large'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.large'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.large'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.large'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.large'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.large'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.large'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.large'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.large'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.large'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.large'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.large'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.large'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.large'; not counting
ERROR:awslimitchecker.services.ec2:ERROR - unknown instance type 'i3.xlarge'; not counting
ERROR:awslimitchecker.services.firehose:Caught exception when trying to use Firehose; perhaps the Firehose service is not available in this region?
Traceback (most recent call last):
  File "/home/users/praetp/.local/lib/python2.7/site-packages/awslimitchecker/services/firehose.py", line 66, in find_usage
    self._find_delivery_streams()
  File "/home/users/praetp/.local/lib/python2.7/site-packages/awslimitchecker/services/firehose.py", line 78, in _find_delivery_streams
    streams = self.conn.list_delivery_streams()
  File "/home/users/praetp/.local/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/users/praetp/.local/lib/python2.7/site-packages/botocore/client.py", line 530, in _make_api_call
    operation_model, request_dict)
  File "/home/users/praetp/.local/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/users/praetp/.local/lib/python2.7/site-packages/botocore/endpoint.py", line 170, in _send_request
    success_response, exception):
  File "/home/users/praetp/.local/lib/python2.7/site-packages/botocore/endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/home/users/praetp/.local/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/home/users/praetp/.local/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/home/users/praetp/.local/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/home/users/praetp/.local/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/home/users/praetp/.local/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/users/praetp/.local/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/home/users/praetp/.local/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/home/users/praetp/.local/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
EndpointConnectionError: Could not connect to the endpoint URL: "https://firehose.ap-southeast-2.amazonaws.com/"
EBS/Throughput Optimized (HDD) volume storage (GiB)  (limit 20480) CRITICAL: 189000
EC2/Running On-Demand r4.large instances             (limit 20) CRITICAL: 139
ELB/Active load balancers                            (limit 20) CRITICAL: 25

**Comment by jantman** [comment]
@spetsnaz84 This is not a failure, but it *is* logging the complete traceback at error-level when it most likely should not; Firehose is [only available](http://docs.aws.amazon.com/general/latest/gr/rande.html#fh_region) in us-east-1, us-west-2 and eu-west-1.

The best fix to this is probably for the next release to not log the traceback for that error. It would also be possible to only check firehose in a hard-coded list of regions, but then that would require a new awslimitchecker release when firehose is enabled in other regions.

Until the next release is out, this error is harmless and can be ignored, or else you explicitly specify the services to check when you run awslimitchecker, and not include Firehose.

**Comment by jantman** [comment]
This has been released as [0.9.0](https://github.com/jantman/awslimitchecker/releases/tag/0.9.0) and is now [live on PyPI](https://pypi.python.org/pypi/awslimitchecker) ([CHANGELOG](http://awslimitchecker.readthedocs.io/en/0.9.0/changes.html#id1)).
