### ISSUE TITLE
'Entries per route table' - static vs propagated

### ISSUE THREAD

**Issue by rgazaryants** [jantman/awslimitchecker#270]
Apparently, there is a hard limit of 100 propagated, and a default soft of 50 static(?) routes per route table. Doesn't looks like limit checker distinguishes between the two & sums them up together, creating false positives.

**Comment by jantman** [comment]
Ok, that's news to me, but I'll look into it and tag this for the next release.

**Comment by jantman** [comment]
Thanks for catching this.

**Comment by jantman** [comment]
This has been released as [0.9.0](https://github.com/jantman/awslimitchecker/releases/tag/0.9.0) and is now [live on PyPI](https://pypi.python.org/pypi/awslimitchecker) ([CHANGELOG](http://awslimitchecker.readthedocs.io/en/0.9.0/changes.html#id1)).
