### ISSUE TITLE
trying to connect to an aws endpoint that doesn't exist

### ISSUE THREAD

**Issue by yuya1211** [jantman/awslimitchecker#271]
Hi,

I am running awslimitchecker on a private ec2 instance, so I need proxy to connect to aws services. So I setup the proxy in the environment for boto3. It then works fine when I run awslimitchecker for us-west-2. However, for us-west-1, I received exception as following, botocore.vendored.requests.exceptions.ConnectionError: HTTPSConnectionPool(host='email.us-west-1.amazonaws.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 404 Not Found',)))

It is trying to connect to a host that does not exist(email.us-west-1.amazonaws.com), SES doesn't have us-west-1 endpoint. Is there anyway to disable this check?

**Comment by jantman** [comment]
There is no way to disable a check, but there is a way to only enable all the other checks. Please see the ``-S|--service`` option in the help output and CLI documentation, or the matching Python options.
