### ISSUE TITLE
Help to align my script to work with several accounts

### ISSUE THREAD

**Issue by alinahazan** [jantman/awslimitchecker#272]
I would like to adjust my script (based on the awslimitchecker) to work with several accounts.

My configuration of all AWS account is in ~/.aws/credentials
From your documentation I found a way to do it in command line:
-P <account name>

Is there a way to do it in python?

The version of awslimitchecker is:
awslimitchecker --version
awslimitchecker 0.8.0 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
awslimitchecker 0.8.0 (see <https://github.com/jantman/awslimitchecker> for source code)

Appreciate your help here,
Alina.

**Comment by jantman** [comment]
Yes, every command line option matches up to a Python option.

The ``-P`` option on the command line is just passed through as the ``profile_name`` parameter on the AwsLimitChecker class. Documentation for the class and its parameters is [here](http://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.checker.html#awslimitchecker.checker.AwsLimitChecker).

At my day job I'm using a wrapper script around awslimitchecker that handles multiple accounts, so if the above documentation isn't enough, I'll see if I can get a not-too-confusing example of how I do it...

**Comment by jantman** [comment]
@alinahazan Is that information sufficient? Can I close this issue?

**Comment by alinahazan** [comment]
Oh, sure, I forgot to update. 
It was very helpful, thanks for your prompt response.
You can close the ticket.

**Comment by jantman** [comment]
Ok great, thank you!
