### ISSUE TITLE
Support i3 instances

### ISSUE THREAD

**Issue by tamsky** [jantman/awslimitchecker#273]
AWS recently announced a new instance type, i3, a Storage Optimized Instance. Add support for it.

**Comment by tamsky** [comment]
Closed by #274

**Comment by jantman** [comment]
Thanks so much for the PR to close this.

Please don't mind the reopening, it's just how I do housekeeping...

**Comment by jantman** [comment]
This has been released as [0.9.0](https://github.com/jantman/awslimitchecker/releases/tag/0.9.0) and is now [live on PyPI](https://pypi.python.org/pypi/awslimitchecker) ([CHANGELOG](http://awslimitchecker.readthedocs.io/en/0.9.0/changes.html#id1)).
