### ISSUE TITLE
add support for a --skip-service flag

### ISSUE THREAD

**Issue by tamsky** [jantman/awslimitchecker#275]
### Feature Description

In some regions, some individual AWS services are not present.

### Use Cases

In the case of `eu-west-2` (London), it has no Firehose service.

When checking limits for this region, rather than needing to specify `--service IAM ElastiCache SES RDS Redshift ELB AutoScaling CloudFormation S3 ElasticBeanstalk EC2 VPC EBS`, I thought it might be nice to be able to simply specify `--skip-service Firehose`

Happy to help test.

PR incoming.

**Comment by tamsky** [comment]
Related #267

**Comment by jantman** [comment]
This has been released as [0.9.0](https://github.com/jantman/awslimitchecker/releases/tag/0.9.0) and is now [live on PyPI](https://pypi.python.org/pypi/awslimitchecker) ([CHANGELOG](http://awslimitchecker.readthedocs.io/en/0.9.0/changes.html#id1)).
