### ISSUE TITLE
DynamoDB support

### ISSUE THREAD

**Issue by jantman** [jantman/awslimitchecker#280]
DynamoDB now has a [DescribeLimits](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_DescribeLimits.html) API call. We should implement a service for this. Default limit documentation is [here](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html).

**Comment by saratlingamarla** [comment]
I'm working on this, just giving you a heads up

**Comment by jantman** [comment]
Cool, thanks!!!

**Comment by saratlingamarla** [comment]
@jantman, I submitted a pull request. Please review it at your convenience.
