### ISSUE TITLE
Elastic File System (EFS) support

### ISSUE THREAD

**Issue by nicksantamaria** [jantman/awslimitchecker#287]
The EFS file system usage could be discovered similarly to the existing ELB implementation.

```
EFS.Client.describe_file_systems()
```
http://boto3.readthedocs.io/en/latest/reference/services/efs.html?highlight=EFS#EFS.Client.describe_file_systems

I have started work on this.

**Comment by jantman** [comment]
This was fixed by your #288 which has been merged into the develop branch and should be released soon.

**Comment by jantman** [comment]
This has been released in [0.11.0](https://github.com/jantman/awslimitchecker/releases/tag/0.11.0)
