### ISSUE TITLE
[Feature Request] configuration file for service limit overrides with multiple AWS accounts

### ISSUE THREAD

**Issue by Mortinke** [jantman/awslimitchecker#325]
## Feature Request

Support json configuration file for service limit overrides with multiple AWS accounts

### Feature Description

This feature request is a combination of #323 and #324. I'd be grateful if we could specify the service limit overrides for each account in a json configuration file something like that:

service_limits.json
```
{
    '<account_id>': {
        '<service_name>': {
          '<limit_name>': <value>,
          '<limit_name>': <value>
        },
        '<service_name>': {
          '<limit_name>': <value>,
          '<limit_name>': <value>
        },
        ...
    },
    '<account_id>': {
        '<service_name>': {
          '<limit_name>': <value>,
          '<limit_name>': <value>
        },
        '<service_name>': {
          '<limit_name>': <value>,
          '<limit_name>': <value>
        },
        ...
    },
    ...
}
```

**Comment by jantman** [comment]
I'm closing this issue as it just duplicates #323 and #324, and I'm responding to each of those separately.

But the gist of the response to this one is the same as to each of those...

For my current employer, we use the Python API to call awslimitchecker, with a wrapper script. We have a ``config/`` directory that contains a bunch of JSON files named like ``limit_overrides_ACCOUNT-ID_REGION.json`` and ``threshold_overrides_ACCOUNT-ID_REGION.json``. Our Python wrapper script is responsible for running awslimitchecker once per region per account, and applying the correct overrides.
