### ISSUE TITLE
Add Support route53 Limits

### ISSUE THREAD

**Issue by jeffwecan** [jantman/awslimitchecker#349]
## Feature Request

See: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html

**Comment by jeffwecan** [comment]
I am currently working on a branch to implement the service referenced in this issue.

**Comment by jeffwecan** [comment]
Missed that there was already an open [PR](https://github.com/jantman/awslimitchecker/pull/345) to this end already. I suppose I'll see if I can lend any assistance there instead :+1:.

**Comment by jantman** [comment]
This has been fixed by #345 which will be released shortly.

**Comment by jantman** [comment]
This was released in [5.0.0](https://github.com/jantman/awslimitchecker/releases/tag/5.0.0) just now, and should be live on PyPI.
