### ISSUE TITLE
Add support for ApiGateway endpoint types limits

### ISSUE THREAD

**Issue by najlen** [jantman/awslimitchecker#365]
ApiGateway has specific limits per ApiGateway endpoint type:

https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html

Maximum number of Regional APIs per account per region | 600 
Maximum number of Private APIs per account per region | 600 
Maximum number of Edge-Optimized APIs per account per region | 120

This is currently not supported and needs to be added.

I guess this limit needs to be divided into more specific limtis:
https://github.com/jantman/awslimitchecker/blob/c5e9ec339e67b1bb97f9f792c9f92c34db5e8994/awslimitchecker/services/apigateway.py#L186

**Comment by jantman** [comment]
Thanks for the heads-up. I'm pretty sure the current API Gateway code in this project was written before private and edge-optimized APIs were available.

PRs would certainly be welcome, and I'd happily assist someone who's not familiar with either this project or contributing to open source in general. Aside from that, I'm not sure when I'll get around to fixing this, sorry.

**Comment by jantman** [comment]
@najlen This will be present in the next release.

**Comment by najlen** [comment]
Thank you @jantman!

**Comment by jantman** [comment]
This has been [released in 6.0.0](https://github.com/jantman/awslimitchecker/releases/tag/6.0.0) and is now [live on PyPI](https://pypi.org/project/awslimitchecker/). Thank you so much!
