### ISSUE TITLE
Update DynamoDB and EFS limits

### ISSUE THREAD

**Issue by bergkampsliew** [jantman/awslimitchecker#390]
There were two AWS announcements to increase the limits for EFS and DDB as below.
https://aws.amazon.com/about-aws/whats-new/2018/12/amazon-dynamodb-increases-the-number-of-global-secondary-indexes-and-projected-index-attributes-you-can-create-per-table/
and
https://aws.amazon.com/about-aws/whats-new/2018/11/amazon-efs-now-supports-1000-file-systems-per-account/
awslimitchecker is currently not updated with the new values.

### Version

6.1.2
(and reproducible using develop branch)

### Installation Method

pip, without virtualenv

### Supporting Software Versions

python 2.7.9
(and also python 3.5.3 when testing with develop branch)

### Actual Output

for example, below is a dynamodb warning alert, same goes with EFS check.
...
DynamoDB/Global Secondary Indexes  (limit 5) WARNING: xxxxxxxxx-table=4
...

### Expected Output

awslimitchecker should use correct values to check for the limits and alert accordingly.

### TrustedAdvisor

-

### Testing Assistance

will make a PR after tested locally

**Comment by jantman** [comment]
This has been released as [6.1.3](https://github.com/jantman/awslimitchecker/releases/tag/6.1.3) via #393 and is now live [on PyPI](https://pypi.org/project/awslimitchecker/).

Thank you so much for the contribution!
