### ISSUE TITLE
set_threshold_override potentially not working for some services

### ISSUE THREAD

**Issue by drandyziegler** [jantman/awslimitchecker#401]
## Bug Report

When reporting a bug in awslimitchecker, please provide all of the following information,
as well as any additional details that may be useful in reproducing or fixing
the issue:

### Version

awslimitchecker version, as reported by ``awslimitchecker --version``
_awslimitchecker 6.1.5 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>_

### Installation Method

updated existing conda environment with 
pip install awslimitchecker -U

### Supporting Software Versions

The output of ``python --version`` and ``virtualenv --version`` in the environment
that awslimitchecker is running in, as well as your operating system type and version.

python --version
Python 2.7.15 :: Anaconda, Inc.

virtualenv --version
15.0.1
(but not using virtualenv for environment but conda)

### Actual Output

use it via python API from my own script

### Expected Output

I already use these lines of code to override the thresholds. 
    connect = AwsLimitChecker(region=region,
                              account_role='role-name-to-assume',
                              account_id=account_number,
                              warning_threshold=50,
                              critical_threshold=90)
    connect.set_threshold_override('EC2', 'VPC Elastic IP addresses (EIPs)',
                                   warn_percent=91, crit_percent=95)
    connect.set_threshold_override('CloudFormation', 'Stacks',
                                   warn_percent=60, crit_percent=85)
    connect.set_threshold_override('EC2',
                                   'Running On-Demand i2.8xlarge instances',
                                   crit_count=1)
    connect.set_threshold_override('VPC', 'VPCs',
                                   warn_percent=80, crit_percent=90)
    connect.set_threshold_override('VPC', 'Internet gateways',
                                   warn_percent=80, crit_percent=90)
    **connect.set_threshold_override('VPC', 'NAT Gateways per AZ',
                                   warn_percent=80, crit_percent=90)**
    connect.set_threshold_override('SES', 'Daily sending quota',
                                   warn_percent=80, crit_percent=90)
    **connect.set_threshold_override('ElastiCache', 'Parameter Groups',
                                   warn_count=15,
                                   warn_percent=80, crit_percent=90)**

At some point in the past I started getting warning for **NAT Gateways per AZ** and  **ElastiCache Parameter Groups** and I added the bold lines above but they don't seem to have any effect. The warning still get issues.

My log message keeps spitting out these lines:
VPC 'NAT Gateways per AZ' usage (3) exceeds warning threshold (limit=5)
ElastiCache 'Parameter Groups' usage (10) exceeds warning threshold (limit=20)

I must be missing something but no matter what I tried I just cannot suppress these two warnings. All the others seem to work fine. I was waiting for new releases hoping that these might fix it but since this has not happened I thought I raise it.

### TrustedAdvisor

No using this.

### Testing Assistance

Happy to test a change.

**Comment by jantman** [comment]
@drandyziegler thanks for opening this issue. You definitely did the right thing by doing so, because I haven't heard anything about this before. The issue tracker here on GitHub is authoritative for this project - if there isn't an issue open for it, I don't know about it.

I'm actually really busy over the next two days or so, but I'll do my best to dig into this sometime this week or this weekend at the latest.

In the mean time, if it's not too much trouble, do you think you could enable debug-level output from awslimitchecker and post that as well (just the awslimitchecker portion, not anything from your wrapper script)?

**Comment by jantman** [comment]
@drandyziegler Any chance you could please add the debug-level output?

**Comment by drandyziegler** [comment]
Hi @jantman , I use https://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.checker.html to instantiate the object within my Python code but cannot find an option to turn on verbose or debug there. Also when I call check_thresholds() I don't see an option to turn on verbose or debug there.
Might need a pointer towards how to generate this information for you.

**Comment by jantman** [comment]
@drandyziegler awslimitchecker uses the standard Python [logging](https://docs.python.org/3/library/logging.html) library for logging.

If you're not already using logging in the script that you call awslimitchecker from, you can get debug-level logging by adding the following to the top of your script:

```
import logging

logging.basicConfig(level=logging.DEBUG, format="%(asctime)s [%(levelname)s %(filename)s:%(lineno)s - %(name)s.%(funcName)s() ] %(message)s")
logger = logging.getLogger()

# suppress boto3 internal logging below WARNING level, as it's VERY verbose and can include secrets
boto3_log = logging.getLogger("boto3")
boto3_log.setLevel(logging.WARNING)
boto3_log.propagate = True

# suppress botocore internal logging below WARNING level, as it's VERY verbose and can include secrets
botocore_log = logging.getLogger("botocore")
botocore_log.setLevel(logging.WARNING)
botocore_log.propagate = True
```

**Comment by drandyziegler** [comment]
Thanks, this did help. It highlighted that my bash script was still executing the old script in the svn repository which did not have the updated thresholds, because I did not get more log message. All works fine.
Sorry to have bothered you.

**Comment by jantman** [comment]
No worries at all, I'm glad that it helped find the problem!
