### ISSUE TITLE
No module named services

### ISSUE THREAD

**Issue by phundisk** [jantman/awslimitchecker#42]
Tried the install directions per the README on Ubuntu 14.04 and Amazon Linux.  I was not able to install the module from pip directly so I attempted to install it via source with a 'python setup.py install'.  When trying to run the binary I get an error "ImportError: No module named services" using python 2.7.

Any chance this will get back into the pip library?  Or is there some other issue when I am installing this?

root@ip-10-0-4-112:~# /usr/local/bin/awslimitchecker
Traceback (most recent call last):
  File "/usr/local/bin/awslimitchecker", line 9, in <module>
    load_entry_point('awslimitchecker==0.1.0', 'console_scripts', 'awslimitchecker')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "build/bdist.linux-x86_64/egg/awslimitchecker/runner.py", line 46, in <module>
  File "build/bdist.linux-x86_64/egg/awslimitchecker/checker.py", line 40, in <module>
ImportError: No module named services

**Comment by jantman** [comment]
@phundisk I'm so sorry, I don't know how I missed this issue from so long ago.

When you tried to install this, the code on ``master`` wasn't in a working state. I just cut the first release this evening, and uploaded it to PyPi literally 5 minutes ago. As far as I can tell (despite the failing Travis builds, which are a problem with the tests themselves) this should be working now, and installable via ``pip install awslimitchecker``.

You'll be the second person using this, so please feel free to pass on any and all feedback.

Thanks,
Jason

**Comment by jantman** [comment]
@phundisk have you been able to give this another try, and confirm if your problem is solved or not?

I've been able to confirm the same issue when installing from ``master`` prior to the 0.1.0 release, and it's fixed for me. So unless I hear otherwise, I'll plan on closing this in a week.

**Comment by jantman** [comment]
As far as I can tell, this should be resolved with the released version on pypi. No response in 27 days (this was opened before there was even an alpha release, against a known-not-working branch); closing.
