### ISSUE TITLE
Cannot get actual value of EC2 type limit

### ISSUE THREAD

**Issue by JayeshThamke** [jantman/awslimitchecker#424]
Source code
```
from awslimitchecker.checker import AwsLimitChecker
c = AwsLimitChecker()
c4_2xlarge = c.get_limits(['EC2'])["EC2"]['Running On-Demand c4.4xlarge instances']
print("limit: " + str(c4_2xlarge.get_limit()))
```
It returns the default AWS limit as `10` rather than actual limit `100` set in AWS EC2 Limits.  
Is there a different API to call for actual EC2 type limit? 
Thanks in advance,
Jayesh

**Comment by jantman** [comment]
Jayesh,

Does your account have Trusted Advisor support?

Per the [documentation on supported limits](https://awslimitchecker.readthedocs.io/en/latest/limits.html#ec2), AWS does not expose the ``Running On-Demand c4.4xlarge instances`` limit via any API, so if you don't have Trusted Advisor you'll need to manually tell awslimitchecker what your limit is if it's not the default. 

Please see the documentation in [Supported Limits](https://awslimitchecker.readthedocs.io/en/latest/limits.html#supported-limits) and [Overriding Limits](https://awslimitchecker.readthedocs.io/en/latest/cli_usage.html#overriding-limits).

**Comment by JayeshThamke** [comment]
Dear Jason, 
Thanks for reply,

Yes, Trusted Advisor enabled but nothing has been configured yet. I saw the documentation on supported limits by API as well as Trusted Limit. 
There is also a trusted a [awslimitchecker.trustedadvisor module](https://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.trustedadvisor.html), can it be helpful to get EC2 instance type's service limit? What methods should I invoke (`_poll`) ? And for EC2 types have no API and TA support (`Running On-Demand c5.9xlarge instances`) how to get their service limit?

Thanks,
Jayesh

**Comment by jantman** [comment]
@JayeshThamke 

No code other than awslimitchecker.checker.AwsLimitChecker should be called externally to the package. The trustedadvisor module is solely used internally by AwsLimitChecker.

For EC2 types that have no API and no TA support, there is currently no way to get the service limit programmatically. You need to manually tell awslimitchecker what the limit is; see the documentation on [overriding limits via the CLI](https://awslimitchecker.readthedocs.io/en/latest/cli_usage.html#overriding-limits) or [via Python](https://awslimitchecker.readthedocs.io/en/latest/python_usage.html#setting-a-limit-override). This _may_ change in the future with #413 .

If you need assistance troubleshooting the TA support, I'll need you to provide all of the information that was in the [Issue Template](https://github.com/jantman/awslimitchecker/blob/master/.github/ISSUE_TEMPLATE.md#bug-report) that you deleted.

**Comment by jantman** [comment]
No response in two weeks; closing. Please reopen this issue with the requested information if you have further questions.
