### ISSUE TITLE
Broken links in the docs

### ISSUE THREAD

**Issue by amosshapira** [jantman/awslimitchecker#433]
Links from https://awslimitchecker.readthedocs.io/en/latest/ to "Code Health" and "Stories in Ready - waffle.io" are broken:
<img width="638" alt="Screen Shot 2019-10-15 at 11 13 23 am" src="https://user-images.githubusercontent.com/654521/66790747-d6109d00-ef3c-11e9-8a73-401daa46730f.png">

Also link to https://waffle.io/jantman/awslimitchecker fails on DNS resolution.

**Comment by jantman** [comment]
@amosshapira Thanks so much for making me aware of this!

**Comment by jantman** [comment]
I hadn't even known that [waffle.io shut down back in May](http://web.archive.org/web/20190315160100/https://blog.waffle.io/farewell-from-waffle-%EF%B8%8F-794da4a72851?gi=3cb9f5e24d3a) and is so gone that their domain and "going away" blog post are even dead. It looks like I'll just use GitHub Projects for that from now on...

**Comment by jantman** [comment]
This has been fixed in the develop branch, and will be present in the next release. Thank you so much!

**Comment by amossc** [comment]
Thanks

**Comment by jantman** [comment]
This has been fixed in [8.0.0](https://github.com/jantman/awslimitchecker/releases/tag/8.0.0) which is now live on [PyPI](https://pypi.org/project/awslimitchecker/) and [Docker Hub](https://hub.docker.com/r/jantman/awslimitchecker/tags). Apologies for any delays in getting this released.
