### ISSUE TITLE
awslimitchecker checkID returned none value

### ISSUE THREAD

**Issue by naorc12** [jantman/awslimitchecker#441]
When reporting a bug in awslimitchecker, please provide all of the following information,
as well as any additional details that may be useful in reproducing or fixing
the issue:

Version
awslimitchecker 4.0.2 / awslimitchecker 7.1.0  (tested on 2 different versions)

Installation Method
pip install awslimitchecker
Not virtualenv

Supporting Software Versions
Python 2.7.6
Description: Ubuntu 14.04.5 LTS

Actual Output
Our script use awslimitchecker, we are getting No data and error message since the last few hours. the problem is that the CheckID value returned is none(this is happened because _get_limit_check_id function that could not find {check['category'] == 'performance' and check['name'] == 'Service Limits'}).
Tried to check it manually to validate, run:
"aws support describe-trusted-advisor-checks --language en"
and i didn not see any checks that under "performance" category and the name is "Service Limits", maybe i misunderstood something here or maybe amazon changed something...

Expected Output
The real limit value.

TrustedAdvisor
Business support.

And here is the output for running "awslimitchecker -r ap-northeast-1 -l -vv":
[limitcheckerDebug.log](https://github.com/jantman/awslimitchecker/files/3788992/limitcheckerDebug.log)

**Comment by jantman** [comment]
@naorc12 Yes, that check likely does not exist for your account anymore. There are a few things going on here at once:

1. The EC2 service limits are drastically changing over this week and the next week, according to [this announcement from AWS](https://aws.amazon.com/about-aws/whats-new/2019/09/vcpu-based-on-demand-instance-limits-are-now-available-in-amazon-ec2/). I'm currently working on a fix for this in #432, and hope to release it this week.
2. It seems that the Trusted Advisor check we've been using, category==performance name=='Service Limits' is going away... it's not present on new accounts and may be disappearing on existing accounts. There is a new entire category for "Service Limits" in Trusted Advisor. However, there is also the new Service Quotas service/API, which is supposed to provide detailed and up-to-the-minute limit information. Issue #413 is open for implementing Service Quotas, and discontinuing use of Trusted Advisor where there's overlap. I plan on implementing this as soon as possible, hopefully this week or this weekend.

I'll keep this issue open to fix this particular bug, and will get the fix in the next release.

Until I get that fix out, you can completely skip using Trusted Advisor for this account [using the --skip-ta command line option](https://awslimitchecker.readthedocs.io/en/latest/cli_usage.html#disabling-trusted-advisor-checks) or, if using the Python API, by [passing use_ta=False to AwsLimitChecker.check_thresholds()](https://awslimitchecker.readthedocs.io/en/latest/python_usage.html#disabling-trusted-advisor).

PS - I see that you're running under Python 2.7.6. According to [PEP 373](https://www.python.org/dev/peps/pep-0373/), Python 2.7 is going to be end-of-life / unsupported on January 1, 2020. Accordingly, per #438, this next release will announce the deprecation of support for Python versions below 3.5, and the release after that will stop testing or officially supporting Python versions below 3.5.

**Comment by jantman** [comment]
A fix for this has been merged to the ``develop`` branch if you'd like to test. It will be included in the next release.

**Comment by jantman** [comment]
And since apparently I was too busy earlier today to remember to be a good person... thank you so much for reporting this, and apologies for the issues!

**Comment by naorc12** [comment]
@jantman Thanks, I'll check it out and of course waiting for the new release

**Comment by jantman** [comment]
This has been fixed in [8.0.0](https://github.com/jantman/awslimitchecker/releases/tag/8.0.0) which is now live on [PyPI](https://pypi.org/project/awslimitchecker/) and [Docker Hub](https://hub.docker.com/r/jantman/awslimitchecker/tags). Apologies for any delays in getting this released.
