### ISSUE TITLE
awslimitchecker checkID returned none value

### ISSUE THREAD

**Issue by Andreyg4** [jantman/awslimitchecker#459]
Version:
awslimitchecker 7.1.0

Installation Method:
pip install awslimitchecker
Not virtualenv

Supporting Software Versions:
Python 2.7.6
Ubuntu 14.04.5 LTS

Actual Output:
Our script is using AWSlimitchecker, and for around 12 hours we are getting No Data and error message.
It was working without any issues before we started seeing this error. 

Expected Output:
The real limit value.

TrustedAdvisor:
Business support.

Output for running "awslimitchecker -r ap-northeast-1 -l -vv":
[LimitChecker.log](https://github.com/jantman/awslimitchecker/files/4225061/LimitChecker.log)

Please let me know if you need any additional information.

**Comment by jantman** [comment]
@Andreyg4 This is related to a breaking API change released by AWS. Please upgrade to awslimitchecker [8.0.0](https://github.com/jantman/awslimitchecker/releases/tag/8.0.0) or newer for the fix.
