### ISSUE TITLE
awslimitchecker unable to find TrustedAdvisor checks

### ISSUE THREAD

**Issue by xRokco** [jantman/awslimitchecker#466]
## Bug Report

When reporting a bug in awslimitchecker, please provide all of the following information,
as well as any additional details that may be useful in reproducing or fixing
the issue:

### Version

Python, 8.0.2

### Installation Method

Using pip, with awslimitchecker in a requirement.txt file
pip install -r requirements.txt --target .

### Supporting Software Versions

➜ python --version            
Python 3.7.5

➜ virtualenv --version
16.7.9

### Actual Output

```
awslimitchecker 8.0.2 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
...
Querying Trusted Advisor checks
Unable to find check with category 'performance' and name 'Service Limits'.
Unable to find 'Service Limits' Trusted Advisor check; not using Trusted Advisor data.
Updating TA limits on all services
```

### Expected Output

Looking at the code, the _get_limit_check_id() function in trustedadvisor.py seems to poll Trusted Advisor for its set of checks and then loop through it, looking for a check with category "performance" and name "Service Limits", but does not find any. 

Doing some research into Trusted Advisor, I can see that there are five separate categories of checks in my account - Cost Optimization, Performance, Security, Fault Tolerance and Service Limits.

However, looking at how Trusted Advisor used to be laid out (at least many years ago) from [this](https://aws.amazon.com/about-aws/whats-new/2014/07/31/aws-trusted-advisor-security-and-service-limits-checks-now-free/) AWS blog post it appears that previously "Service Limits" fell under the "Performance" category, as the awslimitchecker code seems to indicate.

Perhaps I'm missing something but I don't seem to be able to find a way to use Trusted Advisor currently.

### TrustedAdvisor

Business support

### Testing Assistance

Yes

**Comment by jantman** [comment]
@xRokco I'll look into this, thanks for reporting it.

What region are you running in? Unless you're in China or GovCloud, Trusted Advisor will provide no value whatsoever, as every limit that it supports is also provided by either Service Quotas or the individual service's own API. At this point the Trusted Advisor code really only exists to support users in GovCloud and China until those partitions catch up with Service Quotas (which, for all I know, may have happened already).

**Comment by xRokco** [comment]
Yeah we're just in regular region (us-east-2, eu-west-1, etc).
So there is no longer any limits in these regions that are captured by Trusted Advisor that Service Quotas doesn't also capture? I was under the impression that Trusted Advisor checks were still done for a subset of limits but maybe I'm mistaken, if so, this isn't a bug and it can be ignored.

**Comment by jantman** [comment]
@xRokco The Trusted Advisor checks _are_ still done, but appear to essentially be ignored. Looking at the [Supported Limits table in the docs](https://awslimitchecker.readthedocs.io/en/latest/limits.html), every limit outside of China and GovCloud (which still have the per-instance-size EC2 limits) that's reported by Trusted Advisor is also reported by either Service Quotas or the service's own API... and limit values from Service Quotas or API take precedence over Trusted Advisor.

So yeah, Trusted Advisor is not only not providing any additional data, but the data it _does_ provide ends up getting ignored in normal regions.

I'm going to leave this issue open, though, as we should really be either not even attempting TA polling outside of China/Gov, or we should at least get rid of the now-midleading warning messages.

**Comment by skraga** [comment]
Hi, we're using regular AWS and China AWS. Trusted Advisor support will be very good for us as Service Quotas isn't available in China and there are some checks that available via Trusted Advisor but not via Service API.

**Comment by jacobisaliveandwell** [comment]
@jantman I just went through a long rabbit hole with support and can confirm that this endpoint has been removed in January.

**Comment by jantman** [comment]
Thanks, @jacobisaliveandwell. Apologies for any confusion you encountered with this. I'll do my best to get this cleaned up soon.

**Comment by jantman** [comment]
This will be fixed (well, really, worked around) in the next release, by #505.

**Comment by jantman** [comment]
A fix for this issue has been merged to the [develop](https://github.com/jantman/awslimitchecker/tree/develop) branch and is slated for release in 10.0.0 on Monday, December 7, 2020. Anyone who is able to test the fix is strongly encouraged to do so, and comment on this issue with their results. Instructions for installing awslimitchecker from a git branch are available in the [Installing for Development documentation](https://awslimitchecker.readthedocs.io/en/latest/development.html#installing-for-development).
