### ISSUE TITLE
add support for AlertManager as alert provider

### ISSUE THREAD

**Issue by varuzam** [jantman/awslimitchecker#474]
### Feature Description

Alertmanager is widely used for alerting. It would be nice to support it.

```
awslimitchecker \
    --alert-provider=AlertManager \
    --alert-config=endpoints=http://alertmanager1:9093,http://alertmanger2:9093 \
    --alert-config=basic_auth_username=user \
    --alert-config=basic_auth_password=pass
```

### Testing Assistance

I will be able to assist in testing pre-release
code for the feature.

**Comment by jantman** [comment]
Thanks for the suggestion. I've never heard of AlertManager, so I'm not going to be able to test this myself.

I highly doubt that I'll be implementing this myself, but pull requests are welcome, and I'd be happy to merge a PR from anyone who's willing to have a try at implementing it.

**Comment by jantman** [comment]
#476 has been opened with code to implement this. I'll be working to merge that soon. Closing this issue and using the PR for further tracking and discussion.
