### ISSUE TITLE
what is the proper way to use awslimitchecker in python script?

### ISSUE THREAD

**Issue by varuzam** [jantman/awslimitchecker#479]
I would like to run awslimitchecker accross all AWS regions from the python script:
```
import sys, boto3
from awslimitchecker.runner import console_entry_point

client = boto3.client('ec2', region_name='us-east-1')
regions = [region['RegionName'] for region in client.describe_regions()['Regions']]

for region in regions:
    print(f'--- Checking the region {region} ---', flush=True)
    sys.argv = ['script', '-r', region, '--alert-provider=AlertManager', '--alert-config=endpoints=http://alertmanager-0.alertmanager:9093,http://alertmanager-1.alertmanager:9093', '--alert-config=alert_duration=2500']
    console_entry_point()
```
is it the proper way?

**Comment by jantman** [comment]
@varuzam ``console_entry_point()`` should only ever be called from the built-in wrapper script.

For calling it via Python, please see the "Python Usage" page of the documentation: https://awslimitchecker.readthedocs.io/en/latest/python_usage.html

**Comment by jantman** [comment]
Closing this, since there's been no further response. If you have any more questions, please feel free to reopen.
