### ISSUE TITLE
Adding "error_on_warning" flag in the core code

### ISSUE THREAD

**Issue by luoyimu1** [jantman/awslimitchecker#516]
### Feature Description

"error_on_warning" flag is mentioned in the check_aws_limits.py wrapper file, but is it possible to add it into the core code as well?
### Use Cases

This will be very useful in CI/CD pipeline, where the flag could be used to fail the build if hitting warning threshold

### Testing Assistance

Yep, I'd like to help out with testing pre-release
code for the feature.

**Comment by jantman** [comment]
Apologies for waiting so long before replying to this.

When you sat "the core code", do you mean the ``awslimitchecker`` CLI command? If so, this already happens. The ``awslimitchecker`` command uses Nagios-compatible exit codes: zero (0) on success, one (1) if there are warnings, and two (2) if there are criticals.
