### ISSUE TITLE
Incorrect 'VPC security groups per Region' usage

### ISSUE THREAD

**Issue by aperov9** [jantman/awslimitchecker#518]
## Bug Report

The 'VPC security groups per Region' usage value is not correct in combination with VPC sharing. In tested account the `result['EC2']['VPC security groups per Region'].get_current_usage()[0].get_value()` returns a value over 2500 although there was no quota increase. (default limit is 2500)

### Version

awslimitchecker version 10.0.0

### Expected Output

Awslimitchecker should not count all VPC security groups available in a region for one account. This number includes SGs that are owned by other accounts if the VPC is shared between accounts. For the correct number of SGs, it should be filtered by the owner account.

### Testing Assistance

I'm able to assist in testing pre-release.

**Comment by jantman** [comment]
A fix for this has been released in [12.0.0](https://github.com/jantman/awslimitchecker/releases/tag/12.0.0), which is now live [on PyPI](https://pypi.org/project/awslimitchecker/) and [Docker Hub](https://hub.docker.com/r/jantman/awslimitchecker). Thank you so much!
