### ISSUE TITLE
Added to conda

### ISSUE THREAD

**Issue by BastianZim** [jantman/awslimitchecker#520]
Hi,

this is more of an FYI than an issue but I just wanted to let the maintainers know that I added awslimitchecker (and versionfinder since awslimitchecker depends on it) to conda-forge so that it can be downloaded with conda.

The repo is here: https://github.com/conda-forge/awslimitchecker-feedstock and https://github.com/conda-forge/versionfinder-feedstock

Let me know if anyone of the maintainers here would like to be added as maintainers there or if I should make a PR here to add a badge or install instructions. Otherwise, feel free to just close the issue.

Thanks! 😃

**Comment by jantman** [comment]
@BastianZim Apologies for the delay.

Without going into a whole lot of detail here, I haven't been giving awslimitchecker (or any of my other F/OSS projects, though this is the only one that has more than a handful of users) anywhere near the attention that it deserves lately. I've been meaning to fix that, but various personal things have gotten in the way.

I'd be happy to have a PR here with install instructions, and a badge if desired. Regarding maintaining it, I'll sign up for an account, and yes, I'd like to be added as a maintainer... if for no other reason, so that access stays with the current owner of awslimitchecker (me) and can be passed on to the future owner (???) cleanly.

**Comment by BastianZim** [comment]
@jantman No worries at all, totally understood.

Ok great, will do that momentarily. Conda-forge is completely GitHub based so the account will be your GitHub account. I'll stay as a maintainer as well but of course, if you'd like to add someone else at a later date, that can easily be changed.

**Comment by jantman** [comment]
Ok cool, thanks so much!

**Comment by BastianZim** [comment]
Happy to help! 
I have created the PRs that add you as a codeowner so you should get the invite momentarily which will give you push access to the repos. 
But, as I said, I will still stay on and update etc. them so don't feel pressured to actually maintain them. I just like having the upstream owner onboard because that sometimes makes finding issues that occur somehwere between upstream and feedstock easier.

**Comment by BastianZim** [comment]
Just to check, I can currently find the install method mentioned once in the README and once in the docs. Would you like me to add the install instructions in both places or do you prefer a different approach?

**Comment by jantman** [comment]
Cool, thanks so much! Yeah, I definitely agree about having the upstream owner onboard. I've also been the victim of orphaned packages before, so I like to know that if I do eventually pass on ownership of the project, the new owner will have full access.

Hmm... I guess that's some unfortunate duplication. It's up to you... it might be best to put the installation method in the built docs, and just add a line to the README for something like "For Conda install instructions, see the full documentation."

**Comment by BastianZim** [comment]
Yeah, fully agree! Have had that too...!

Since installing with conda is relatively easy (It's basically just `conda install -c conda-forge awslimitchecker`) I would suggest adding this command to the README along with a badge indicating the newest version that is currently available (Like so: [![Conda Version](https://img.shields.io/conda/vn/conda-forge/awslimitchecker.svg)](https://anaconda.org/conda-forge/awslimitchecker)) and then explain the process of creating conda environments and installing the package (As sort of outlined here https://github.com/conda-forge/awslimitchecker-feedstock/blob/master/README.md) in the docs. 
What do you think?

**Comment by jantman** [comment]
Sounds good to me! If you can open a PR for that, I'll get it merged & released the next time there's a release... which I hope will be relatively soon.

**Comment by BastianZim** [comment]
Perfect! Gotta run now but I'll create the PR tomorrow and keep you updated. Thanks!

**Comment by BastianZim** [comment]
@jantman Just wanted to check in if there's anything else you'd like me to add?

**Comment by BastianZim** [comment]
Just gently bumping this again @jantman

**Comment by BastianZim** [comment]
Hi @jantman just wanted to check in if you already had some time to review this, thanks!

**Comment by jantman** [comment]
A fix for this has been released in [11.0.0](https://github.com/jantman/awslimitchecker/releases/tag/11.0.0), which is now live [on PyPI](https://pypi.org/project/awslimitchecker/). Thank you so much, and apologies for the delay.

**Comment by BastianZim** [comment]
Thank you! I'll update the conda-forge version just now.
