### ISSUE TITLE
EBS(Provisioned IOPS) not getting limits from quota/trusted advisor

### ISSUE THREAD

**Issue by pritam2277** [jantman/awslimitchecker#521]
## Bug Report

As per the documentation [(https://awslimitchecker.readthedocs.io/en/latest/limits.html#ebs)] , EBS(Provisioned IOPS) should get current limits from quotas and trusted-advisor(if available). It gives me current limit as 200,000(hard-coded value) and not the value from quota.  Is above documentation correct or awslimitchecker is unable to get current limits from quota/trusted advisor?

Also when I run "awslimitchecker -l", it shows all limit values along with API or quota in brackets depending on from where it's getting the limits. I see few limits takes default values(no mention of API or Quotas) while documentation says the otherwise.

FYI : I am running awslimitchecker on account which has business support enabled.
       New Default quota for EBS(Provisioned IOPS) is 300,000.

### Version

[awslimitchecker version, as reported by ``awslimitchecker --version`` =10.0.0

### Installation Method

awslimitchecker was installed using virtualenv.

### Supporting Software Versions

python --version 3.9.1

### Actual Output

C:\Users\pyaduvansh>awslimitchecker -S EBS
awslimitchecker 10.0.0 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
EBS/Provisioned IOPS  (limit 200000) [33mWARNING: 160000[0m

### Expected Output
C:\Users\pyaduvansh>aws service-quotas get-service-quota --service-code ebs --quota-code L-B3A130E6
{
    "Quota": {
        "ServiceCode": "ebs",
        "ServiceName": "Amazon Elastic Block Store (Amazon EBS)",
        "QuotaArn": "arn:aws:servicequotas:us-east-1:54*********88:ebs/L-B3A130E6",
        "QuotaCode": "L-B3A130E6",
        "QuotaName": "IOPS for Provisioned IOPS SSD (io1) volumes",
        "Value": 310000.0,
        "Unit": "None",
        "Adjustable": true,
        "GlobalQuota": false
    }
}

### Testing Assistance
I will be able to assist in testing pre-releasecode for the feature.

Thanks,
Pritam

**Comment by pritam2277** [comment]
@jantman . Please have a look.

**Comment by jwu2** [comment]
There are similar issues with some other EBS limits too. For example:

- General Purpose (SSD) volume storage (GiB)
- Magnetic volume storage (GiB)

These are returning value of 307200 instead of 300000 (default) for limits.

In addition, SSD (gp3) and SSD (io2) metrics are missing. Active Volumes on longer exists.

Please refer to https://docs.aws.amazon.com/general/latest/gr/ebs-service.html for default limits.

Possibly a time to revisit the EBS module.

**Comment by jantman** [comment]
A fix for this has been released in [12.0.0](https://github.com/jantman/awslimitchecker/releases/tag/12.0.0), which is now live [on PyPI](https://pypi.org/project/awslimitchecker/) and [Docker Hub](https://hub.docker.com/r/jantman/awslimitchecker). Thank you so much!
