### ISSUE TITLE
EIPs quota names changed by AWS

### ISSUE THREAD

**Issue by sean-zou** [jantman/awslimitchecker#527]
## Bug Report

According to AWS support:
The below changes were made to Quota Names:
Quota Code: L-0263D0A3
Old Quota Name: Number of EIPs - VPC EIPs
New Quota Name: EC2-VPC Elastic IPs

Quota Code: L-CEED54BB
Old Quota Name: Elastic IP addresses for EC2-Classic
New Quota Name: EC2-Classic Elastic IPs

Quota Name and Description are subject to change, QuotaCode is the one that would remain constant with other changes to quota properties.

### Suggested fix

I'd suggest to add a property called quota_code in [limit.py ](https://github.com/jantman/awslimitchecker/blob/develop/awslimitchecker/)and remove all hardcoded quota names in [ec2.py ](https://github.com/jantman/awslimitchecker/blob/develop/awslimitchecker/services/ec2.py)

### Version

10.0.0

**Comment by jantman** [comment]
A fix for this has been released in [12.0.0](https://github.com/jantman/awslimitchecker/releases/tag/12.0.0), which is now live [on PyPI](https://pypi.org/project/awslimitchecker/) and [Docker Hub](https://hub.docker.com/r/jantman/awslimitchecker). Thank you so much!
