### ISSUE TITLE
Incorrect usage count for Rules per network ACL

### ISSUE THREAD

**Issue by jwu2** [jantman/awslimitchecker#538]
## Bug Report

When reporting a bug in awslimitchecker, please provide all of the following information,
as well as any additional details that may be useful in reproducing or fixing
the issue:

### Version

11.0.0

### Installation Method

Any

### Supporting Software Versions

Python 3.8

### Actual Output

Usage count appears to be combined total of ingress and egress rules

### Expected Output

Usage should be counted separately for ingress and egress. According to https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html:
This is the one-way quota for a single network ACL.

### Testing Assistance
I will assist with testing

**Comment by jwu2** [comment]
Should we have two limits instead?
- Rules per network ACL ingress
- Rules per network ACL egress

**Comment by jwu2** [comment]
According to AWS support:
The statement in quotas means that the limit of 20 applies separately to ingress rules or egress rules (as well as ipv4 and ipv6).
For example,

you have an ACL with 15 ingress rules and 5 egress rules (all for ipv4):
- you can add 5 more ingress rules and 15 more egress rules independently, limit of 20 is for each direction - so you can have 20 ingress and 20 egress rules at the same time in 1 ACL.

If either of the direction reaches the limit - you will get error when trying to add more rules to that direction, but you still will be able to add rules to the other until it reaches its limit.

Also, this quota is separate for ipv4 and ipv6, means you can have in an ACL (20 ipv4 + 20 ipv6) ingress rules and (20 ipv4 + 20 ipv6) egress rules = total of 80 rules in 1 ACL.

**Comment by jwu2** [comment]
#543

**Comment by jantman** [comment]
A fix for this has been released in [12.0.0](https://github.com/jantman/awslimitchecker/releases/tag/12.0.0), which is now live [on PyPI](https://pypi.org/project/awslimitchecker/) and [Docker Hub](https://hub.docker.com/r/jantman/awslimitchecker). Thank you so much!
