### ISSUE TITLE
Add support for CloudWatch limits

### ISSUE THREAD

**Issue by sean-zou** [jantman/awslimitchecker#550]
## Feature Request

Add support for CloudWatch limits

### Feature Description

I am especially interested in checking the usage of the following Quotas:
L-8BC498D4: Rate of PutMetricData requests

List of available Quotas:

> L-C1FE0F5C Canary limit
> L-DBD11BCC Number of Contributor Insights rules
> L-25E8DC37 Rate of DeleteAlarms requests
> L-E1508405 Rate of DeleteDashboards requests
> L-7193C790 Rate of DescribeAlarmHistory requests
> L-21CB40A4 Rate of DescribeAlarms requests
> L-E2310E7A Rate of DescribeAlarmsForMetric requests
> L-D750D224 Rate of DisableAlarmActions requests
> L-CA907765 Rate of EnableAlarmActions requests
> L-E82C279D Rate of GetDashboard requests
> L-5E141212 Rate of GetMetricData requests
> L-EE839489 Rate of GetMetricStatistics requests
> L-6FCAAA2E Rate of GetMetricWidgetImage requests
> L-69C44FFD Rate of ListDashboards requests
> L-05D334F0 Rate of ListMetrics requests
> L-B6C4D57E Rate of ListTagsForResource requests
> L-6753900D Rate of PutDashboard requests
> L-0720E68F Rate of PutMetricAlarm requests
> L-8BC498D4 Rate of PutMetricData requests
> L-68B0DFE2 Rate of SetAlarmState requests
> L-4609795C Rate of TagResource requests
> L-6929DE8C Rate of UntagResource requests

### Testing Assistance

I will be able to assist in testing pre-release code for the feature.

**Comment by jantman** [comment]
@sean-zou Even if the usage data for these is easily available, awslimitchecker doesn't really lend itself to checking "Rate of" limits, as those would require it to be run very frequently. Currently, all "Rate of" limits are ignored by awslimitchecker because of this limitation (most users run awslimitchecker at most a few times a day).

I'm going to close this for now, but I'd be open to seeing an example implementation if you'd like.

**Comment by sean-zou** [comment]
@jantman Cloud Custodian has an [implementation](https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/quotas.py#L99-L100) which checks the usage metrics on CloudWatch, which works on service quotas that return a UsageMetric attribute such as the one mentioned above.
