### ISSUE TITLE
Allow custom datadog host

### ISSUE THREAD

**Issue by rafaellima** [jantman/awslimitchecker#551]
## Feature Request

The Datadog API host is currently hardcoded as: `https://api.datadoghq.com`. For anyone using a Datadog EU site, [another host is used](https://docs.datadoghq.com/api/latest/authentication/), otherwise the authentication fails.

### Feature Description

Add a new option `--metrics-host` or have a custom environment variable `DATADOG_HOST` for that use case.

### Use Cases

Any user in the EU that has a custom Datadog host.

### Testing Assistance

I will be able to assist in testing pre-release code for the feature.

**Comment by jantman** [comment]
A fix for this will be in the next release, which will be out today. The hard-coded host will be able to be overridden either via a ``DATADOG_HOST`` environment variable or a ``--metrics-config=host=VALUE`` command-line parameter.
