### ISSUE TITLE
add support for ElasticBeanstalk

### ISSUE THREAD

**Issue by jantman** [jantman/awslimitchecker#70]
Add support for ElasticBeanstalk, especially Versions.

**Comment by jantman** [comment]
Limits: http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_elastic_beanstalk

IAM Permissions: http://docs.aws.amazon.com/IAM/latest/UserGuide/list_elasticbeanstalk.html

There doesn't appear to be an API for limits or usage.

**Comment by bflad** [comment]
Hey @jantman -- we started using your tool today in our environments and its been really helpful. We'd love to see Beanstalk support in here as we have some other homegrown tooling to currently handle that monitoring. Do you have any code written for this so far? I don't mind picking this up wherever it stands.

**Comment by jantman** [comment]
@bflad I don't have any code written yet, but I think the implementation should be pretty simple. I'd be happy beyond words if you'd like to tackle it. If so, feel free to reach out to me with any questions; I'm usually available more or less 0800-1700 GMT-5.

Some resources to help:
* development docs on [Adding New Services](https://awslimitchecker.readthedocs.org/en/latest/development.html#adding-new-services) (note there's a [awslimitchecker/services/addservice](https://github.com/jantman/awslimitchecker/blob/master/awslimitchecker/services/addservice) Python script that gives you a good starting template of the service file and test file.
* commit where I added SES, as an example: https://github.com/jantman/awslimitchecker/commit/9d78c09cc090004ed23c1daf5d0883085ee315a4
* note that all of the documentation is automatically generated (including the services list, etc.)
* If there's TrustedAdvisor support or an API for limits, that should be used. If you don't have access to TrustedAdvisor, I can work on and/or test that part.

I'm extremely happy to have interest in contributing code. Due to the unclear legal standing of OSS contributions with my employer, I currently exclusively work on this on my personal time... and I've been rather busy with other obligations lately.

**Comment by bflad** [comment]
Submitted PR: https://github.com/jantman/awslimitchecker/pull/176

There is currently no API or TA support for fetching Beanstalk limits, so we're stuck with the manual defaults and overrides.

Thanks for all the helpful documentation, I'm still fairly new with Python in general and you made it much easier!

**Comment by jantman** [comment]
This is fixed in #180 which is now merged to develop and will be released shortly.

**Comment by jantman** [comment]
fixed in 0.4.2, which was just released
