### ISSUE TITLE
Switch to boto3?

### ISSUE THREAD

**Issue by jantman** [jantman/awslimitchecker#95]
[boto3](https://github.com/boto/boto3) is out and is where new development is supposedly happening, and is also the [official AWS python SDK](http://aws.amazon.com/sdk-for-python/). Look into how difficult it would be to transition to using it.

**Comment by mr337** [comment]
We are transitioning all of our stuff from boto2 to boto3. Would recommend!

**Comment by jantman** [comment]
See also the [Migrating from boto 2.x guide](https://boto3.readthedocs.org/en/latest/guide/migration.html)

**Comment by jantman** [comment]
I should do #112 and #114 before releasing this.

**Comment by jantman** [comment]
Before merging:

1. Refactor test data into a class/module
2. Look into how boto3 handles default regions. All of ALC lets the default region be ``None`` and passes this through to boto. With boto3, there's a change to the underlying environment variable use. I found this out by running ``awslimitchecker -vv -u -S ElastiCache`` after 32416b7, and got vastly different results from the latest release. It turns out that the new boto3 code is connecting to ``us-west-2``. It appears that with boto2, if you set the ``AWS_ACCESS_KEY_ID`` and ``AWS_SECRET_ACCESS_KEY`` environment variables, it completely ignores ``~/.aws/credentials``. With boto3, however, if you have a ``[default]`` section in ``~/.aws/credentials`` and then export the key env vars, it still uses the ``region`` from ``~/.aws/credentials``.

**Comment by jantman** [comment]
The [tests](https://travis-ci.org/jantman/awslimitchecker/builds/106379031) on the [latest commit](https://github.com/jantman/awslimitchecker/commit/e666bd935b3e2e71a3996439d807a331e0081900) for this failed.

It turns out that the boto3/botocore code being called by ``result_fixtures.get_boto3_resource_model()`` is actually making an HTTP request to 169.254.169.254, the AWS instance metadata service, when running in Travis. This didn't seem to be happening when running locally. This happens when it creates the ``Session`` object.

So the boto3 ``Session.resource()`` calls ``botocore.session.Session.create_client()`` which, [if aws_secret_access_key is None](https://github.com/boto/botocore/blob/1.3.23/botocore/session.py#L788), calls [Session.get_credentials()](https://github.com/boto/botocore/blob/1.3.23/botocore/session.py#L423). That in turn calls ``self._components.get_component('credential_provider').load_credentials()``

[provider.load()](https://github.com/boto/botocore/blob/1.3.23/botocore/credentials.py#L874) for the first provider in Travis appears to go to [InstanceMetadataProvider.load()](https://github.com/boto/botocore/blob/1.3.23/botocore/credentials.py#L342]. This goes to ``fetcher.retrieve_iam_role_credentials()`` which is [utils.InstanceMetadataFetcher](https://github.com/boto/botocore/blob/1.3.23/botocore/utils.py#L157).

So... I think the real question is that InstanceMetadataProvider seems to be either not loading/being loaded in my local test (on phoenix), or is somehow exiting before pytest-blockage catches the request???

The key appears to be [here](https://github.com/boto/botocore/blob/1.3.23/botocore/credentials.py#L64) where ``create_credential_resolver()`` adds the metadata provider. There's some stuff that comes from session config variables.

So I *think* that what's going on here is, based on that list in that function, is that the instance metadata provider is never getting called locally. I should add some instrumentation to my local botocore code to confirm this.

Another way around it might be that the [docstring](https://github.com/boto/botocore/blob/1.3.23/botocore/credentials.py#L37) for ``create_credential_resolver()`` says, "Create a default credential resolver." Maybe I can somehow specify a non-default resolver?

Furthermore, am I sure that my function will even work without credentials?

https://github.com/boto/boto3/blob/1.2.3/boto3/session.py#L26 does have a param to pass in a botocore session, instead of creating a new one.

**Comment by jantman** [comment]
Ok, I reproduced the blockage failures locally. d'oh. I didn't move ``~/.aws/config`` and it was sourcing credentials from there. Now, how to figure out how to get rid of the InstanceMetadataProvider (aside from possibly just mocking it out)...

**Comment by jantman** [comment]
Ok, I fixed the InstanceMetadata one by creating the botocore session directly, and passing in a ``session_vars`` dict that set ``metadata_service_num_attempts`` to 0. But I'm also seeing the same problem from ``retrieve_iam_role_credentials()``.

It looks like the simplest way to fix this is to export some bogus AWS credential environment vars, which will prevent any of the HTTP-firing credential providers from working.

**Comment by jantman** [comment]
Fix was merged in #119
